"use client";
import { useEffect, useMemo, useState } from "react";
import { collections, experiences, fleet, mapPoints } from "../../content/mlt";
import { collectionDe } from "../../content/i18n";
const rates: Record<string, [number, number]> = { freedom: [150, 220], signature: [250, 400], concierge: [450, 700], private: [2000, 4000] };
const texts = {
  en: { edit: "Edit journey", print: "Save as PDF / Print", document: "Private travel proposal · Europe 2026", prepared: "Prepared exclusively for", title: "Your private", titleEm: "road expedition", days: "days", proposition: "The proposition", intro: "Not simply a motorhome rental, but a considered way to experience Europe. Your route, residence and level of support have been composed into one private journey.", residence: "Travelling residence", service: "Service collection", route: "Proposed route", chapters: "A journey in chapters", routeNote: "The sequence is indicative. Your MLT Concierge will refine driving times, seasonal access and overnight stays.", arrival: "Arrival", final: "Final chapter", enRoute: "En route", selected: "Selected experiences", beyond: "Beyond the road", curated: "To be curated with you", noExtras: "Your concierge will suggest private experiences after learning your preferences.", investment: "Indicative investment", based: (days: number, name: string) => `Based on ${days} days in the ${name} Collection. Experiences and third-party reservations are quoted separately.`, daily: "Daily collection rate", status: "Proposal status", availability: "Subject to availability", disclaimer: "This proposal is an initial travel concept and does not constitute a binding reservation.", continue: "Continue with MLT Concierge" },
  de: { edit: "Reise bearbeiten", print: "Als PDF speichern / Drucken", document: "Persönliches Reiseangebot · Europa 2026", prepared: "Exklusiv vorbereitet für", title: "Ihre private", titleEm: "Road Expedition", days: "Tage", proposition: "Das Reisekonzept", intro: "Nicht einfach eine Reisemobilmiete, sondern eine durchdachte Art, Europa zu erleben. Route, mobile Residenz und Betreuung wurden zu einer persönlichen Reise komponiert.", residence: "Mobile Residenz", service: "Service-Kollektion", route: "Vorgeschlagene Route", chapters: "Eine Reise in Kapiteln", routeNote: "Die Reihenfolge ist vorläufig. Ihr MLT Concierge optimiert Fahrzeiten, saisonale Zufahrten und Übernachtungsorte.", arrival: "Anreise", final: "Finales Kapitel", enRoute: "Unterwegs", selected: "Gewählte Erlebnisse", beyond: "Mehr als eine Reise", curated: "Persönlich für Sie kuratiert", noExtras: "Ihr Concierge empfiehlt private Erlebnisse, sobald wir Ihre Wünsche kennen.", investment: "Richtpreis", based: (days: number, name: string) => `Basierend auf ${days} Tagen in der ${name} Collection. Erlebnisse und Reservierungen bei Drittanbietern werden separat angeboten.`, daily: "Tagessatz der Kollektion", status: "Status des Angebots", availability: "Vorbehaltlich Verfügbarkeit", disclaimer: "Dieses Angebot ist ein erster Reiseentwurf und stellt keine verbindliche Reservierung dar.", continue: "Weiter mit dem MLT Concierge" },
} as const;
const countryDe: Record<string, string> = { Italy: "Italien", Austria: "Österreich", Germany: "Deutschland" };
export default function ProposalPage() {
  const [ready, setReady] = useState(false); const [locale, setLocale] = useState<"en" | "de">("en"); const [data, setData] = useState({ country: "Italy", guests: "2 guests", vehicle: "granduca", collection: "signature", arrival: "2026-09-17", departure: "2026-09-27", route: ["dolomites", "como"], extras: [] as string[] });
  useEffect(() => { const q = new URLSearchParams(location.search); const dates = q.get("dates")?.split("_"); setLocale(q.get("lang") === "de" || (!q.get("lang") && localStorage.getItem("mlt-locale") === "de") ? "de" : "en"); setData({ country: q.get("country") || "Italy", guests: q.get("guests") || "2 guests", vehicle: q.get("vehicle") || "granduca", collection: q.get("collection") || "signature", arrival: dates?.[0] || "2026-09-17", departure: dates?.[1] || "2026-09-27", route: q.get("route")?.split(",").filter(Boolean) || ["dolomites", "como"], extras: q.get("extras")?.split(",").filter(Boolean) || [] }); setReady(true); }, []);
  const vehicle = fleet.find((item) => item.id === data.vehicle) || fleet[1]; const sourceCollection = collections.find((item) => item.id === data.collection) || collections[1]; const collection = locale === "de" ? { ...sourceCollection, ...collectionDe[sourceCollection.id] } : sourceCollection; const duration = useMemo(() => Math.max(1, Math.round((new Date(data.departure).getTime() - new Date(data.arrival).getTime()) / 86400000)), [data.arrival, data.departure]); const range = rates[collection.id]; const t = texts[locale]; const money = (value: number) => new Intl.NumberFormat(locale === "de" ? "de-DE" : "en-GB", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value); const localizedCountry = locale === "de" ? countryDe[data.country] || data.country : data.country;
  const switchLanguage = (lang: "en" | "de") => { const q = new URLSearchParams(location.search); q.set("lang", lang); history.replaceState(null, "", `${location.pathname}?${q}`); setLocale(lang); };
  if (!ready) return <main className="proposal-page proposal-loading">MLT…</main>;
  return <main className="proposal-page"><nav className="proposal-actions"><a href={`/plan${location.search}`}>← {t.edit}</a><div><button className={locale === "en" ? "active" : ""} onClick={() => switchLanguage("en")}>EN</button><button className={locale === "de" ? "active" : ""} onClick={() => switchLanguage("de")}>DE</button></div><button onClick={() => window.print()}>{t.print}</button></nav><article className="proposal-document">
    <header className="proposal-cover"><div className="proposal-brand"><strong>MLT</strong><span>Move. Live. Travel.</span></div><p>{t.document}</p><div><small>{t.prepared}</small><h1>{t.title}<br /><em>{t.titleEm}</em></h1><p>{localizedCountry} · {data.arrival} — {data.departure}</p></div><footer><span>{collection.name} Collection</span><span>{duration} {t.days}</span><span>{data.guests}</span></footer></header>
    <section className="proposal-intro"><p className="section-label">{t.proposition}</p><h2>{collection.promise}</h2><p>{t.intro}</p></section>
    <section className="proposal-overview"><div><small>{t.residence}</small><h3>{vehicle.name}</h3><p>{vehicle.category} · {vehicle.specs.join(" · ")}</p></div><div><small>{t.service}</small><h3>{collection.name}</h3><p>{collection.inclusions.join(" · ")}</p></div></section>
    <section className="proposal-itinerary"><div className="proposal-section-head"><div><p className="section-label">{t.route}</p><h2>{t.chapters}</h2></div><p>{t.routeNote}</p></div><ol>{data.route.map((id, index) => { const place = mapPoints.find((item) => item.id === id); return place && <li key={id}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{place.name}</h3><p>{locale === "de" ? countryDe[place.country] || place.country : place.country} · {place.type}</p></div><b>{index === 0 ? t.arrival : index === data.route.length - 1 ? t.final : t.enRoute}</b></li>; })}</ol></section>
    <section className="proposal-experiences"><p className="section-label">{t.selected}</p><h2>{data.extras.length ? t.beyond : t.curated}</h2><div>{data.extras.length ? data.extras.map((id) => { const item = experiences.find((experience) => experience.id === id); return item && <article key={id}><small>{item.eyebrow}</small><h3>{item.title}</h3><p>{item.detail}</p></article>; }) : <p>{t.noExtras}</p>}</div></section>
    <section className="proposal-investment"><div><p className="section-label">{t.investment}</p><h2>{money(range[0] * duration)} — {money(range[1] * duration)}</h2><p>{t.based(duration, collection.name)}</p></div><aside><small>{t.daily}</small><strong>{collection.rate}</strong><small>{t.status}</small><strong>{t.availability}</strong></aside></section>
    <footer className="proposal-footer"><div className="proposal-brand"><strong>MLT</strong><span>Move. Live. Travel.</span></div><p>{t.disclaimer}</p><a href={`/plan${location.search}`}>{t.continue} →</a></footer>
  </article></main>;
}
