"use client";
import { useEffect, useMemo, useState } from "react";
import { collections, experiences, fleet, mapPoints } from "../../content/mlt";
const rates: Record<string, [number, number]> = { freedom: [150, 220], signature: [250, 400], concierge: [450, 700], private: [2000, 4000] };
const money = (value: number) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value);
export default function ProposalPage() {
  const [ready, setReady] = useState(false); const [data, setData] = useState({ country: "Italy", guests: "2 guests", vehicle: "granduca", collection: "signature", arrival: "2026-09-17", departure: "2026-09-27", route: ["dolomites", "como"], extras: [] as string[] });
  useEffect(() => { const q = new URLSearchParams(location.search); const dates = q.get("dates")?.split("_"); setData({ country: q.get("country") || "Italy", guests: q.get("guests") || "2 guests", vehicle: q.get("vehicle") || "granduca", collection: q.get("collection") || "signature", arrival: dates?.[0] || "2026-09-17", departure: dates?.[1] || "2026-09-27", route: q.get("route")?.split(",").filter(Boolean) || ["dolomites", "como"], extras: q.get("extras")?.split(",").filter(Boolean) || [] }); setReady(true); }, []);
  const vehicle = fleet.find((item) => item.id === data.vehicle) || fleet[1]; const collection = collections.find((item) => item.id === data.collection) || collections[1]; const duration = useMemo(() => Math.max(1, Math.round((new Date(data.departure).getTime() - new Date(data.arrival).getTime()) / 86400000)), [data.arrival, data.departure]); const range = rates[collection.id];
  if (!ready) return <main className="proposal-page proposal-loading">Preparing your private proposal…</main>;
  return <main className="proposal-page"><nav className="proposal-actions"><a href={`/plan${location.search}`}>← Edit journey</a><button onClick={() => window.print()}>Save as PDF / Print</button></nav><article className="proposal-document">
    <header className="proposal-cover"><div className="proposal-brand"><strong>MLT</strong><span>Move. Live. Travel.</span></div><p>Private travel proposal · Europe 2026</p><div><small>Prepared exclusively for</small><h1>Your private<br /><em>road expedition</em></h1><p>{data.country} · {data.arrival} — {data.departure}</p></div><footer><span>{collection.name} Collection</span><span>{duration} days</span><span>{data.guests}</span></footer></header>
    <section className="proposal-intro"><p className="section-label">The proposition</p><h2>{collection.promise}</h2><p>Not simply a motorhome rental, but a considered way to experience Europe. Your route, residence and level of support have been composed into one private journey.</p></section>
    <section className="proposal-overview"><div><small>Travelling residence</small><h3>{vehicle.name}</h3><p>{vehicle.category} · {vehicle.specs.join(" · ")}</p></div><div><small>Service collection</small><h3>{collection.name}</h3><p>{collection.inclusions.join(" · ")}</p></div></section>
    <section className="proposal-itinerary"><div className="proposal-section-head"><div><p className="section-label">Proposed route</p><h2>A journey in chapters</h2></div><p>The sequence is indicative. Your MLT Concierge will refine driving times, seasonal access and overnight stays.</p></div><ol>{data.route.map((id, index) => { const place = mapPoints.find((item) => item.id === id); return place && <li key={id}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{place.name}</h3><p>{place.country} · {place.type}</p></div><b>{index === 0 ? "Arrival" : index === data.route.length - 1 ? "Final chapter" : "En route"}</b></li>; })}</ol></section>
    <section className="proposal-experiences"><p className="section-label">Selected experiences</p><h2>{data.extras.length ? "Beyond the road" : "To be curated with you"}</h2><div>{data.extras.length ? data.extras.map((id) => { const item = experiences.find((experience) => experience.id === id); return item && <article key={id}><small>{item.eyebrow}</small><h3>{item.title}</h3><p>{item.detail}</p></article>; }) : <p>Your concierge will suggest private experiences after learning your preferences.</p>}</div></section>
    <section className="proposal-investment"><div><p className="section-label">Indicative investment</p><h2>{money(range[0] * duration)} — {money(range[1] * duration)}</h2><p>Based on {duration} days in the {collection.name} Collection. Experiences and third-party reservations are quoted separately.</p></div><aside><small>Daily collection rate</small><strong>{collection.rate}</strong><small>Proposal status</small><strong>Subject to availability</strong></aside></section>
    <footer className="proposal-footer"><div className="proposal-brand"><strong>MLT</strong><span>Move. Live. Travel.</span></div><p>This proposal is an initial travel concept and does not constitute a binding reservation.</p><a href={`/plan${location.search}`}>Continue with MLT Concierge →</a></footer>
  </article></main>;
}
