"use client";

import { FormEvent, useCallback, useEffect, useRef, useState } from "react";

type Conversation={id:number;name:string;email:string;locale:string;status:string;unread_operator:number;last_message:string;last_message_at:string};
type Message={id:number;sender_type:"client"|"operator";sender_name:string;body:string;created_at:string};
type DeskData={operator:{name:string;role:"admin"|"manager"};conversations:Conversation[];conversation:Conversation|null;messages:Message[];unread:number;operatorsOnline:number;stats?:{replies:number;clients:number;repliesToday:number}};
type DeskLocale="en"|"de"|"ru";

const copy={
 en:{live:"Live chat desk",home:"Dashboard",admin:"Admin panel",notifications:"Enable notifications",logout:"Sign out",support:"MLT / SUPPORT",messages:"Messages",search:"Search clients",client:"CLIENT",reply:"Write a reply…",sending:"Sending…",send:"Send reply →",select:"Select a conversation",automatic:"New client messages appear here automatically.",restricted:"Chat access restricted",signin:"Sign in →",newMessage:"New message from a client"},
 de:{live:"Live-Chat",home:"Übersicht",admin:"Adminbereich",notifications:"Benachrichtigungen",logout:"Abmelden",support:"MLT / SUPPORT",messages:"Nachrichten",search:"Kunden suchen",client:"KUNDE",reply:"Antwort schreiben…",sending:"Wird gesendet…",send:"Antwort senden →",select:"Konversation auswählen",automatic:"Neue Kundennachrichten erscheinen hier automatisch.",restricted:"Chat-Zugriff eingeschränkt",signin:"Anmelden →",newMessage:"Neue Nachricht von einem Kunden"},
 ru:{live:"Рабочий чат",home:"Главная",admin:"Панель администратора",notifications:"Включить уведомления",logout:"Выйти",support:"MLT / ПОДДЕРЖКА",messages:"Сообщения",search:"Поиск клиентов",client:"КЛИЕНТ",reply:"Написать ответ…",sending:"Отправка…",send:"Отправить →",select:"Выберите диалог",automatic:"Новые сообщения клиентов появляются здесь автоматически.",restricted:"Доступ к чату ограничен",signin:"Войти →",newMessage:"Новое сообщение от клиента"},
} as const;

async function chatApi(action:string,payload:Record<string,unknown>={}){const token=localStorage.getItem("mlt-account-token")||"";const response=await fetch("/api/chat.php",{method:"POST",cache:"no-store",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({action,...payload})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Request failed");return data as DeskData;}

export default function ChatDesk({requiredRole}:{requiredRole?:"admin"|"manager"}){
 const [data,setData]=useState<DeskData|null>(null),[selected,setSelected]=useState(()=>typeof location==="undefined"?0:Number(new URLSearchParams(location.search).get("conversation")||0)),[error,setError]=useState(""),[sending,setSending]=useState(false),[search,setSearch]=useState(""),[locale,setLocale]=useState<DeskLocale>("en");
 const unreadRef=useRef(0),listRef=useRef<HTMLDivElement>(null),t=copy[locale];
 useEffect(()=>{const saved=localStorage.getItem("mlt-operations-locale");if(saved==="en"||saved==="de"||saved==="ru")setLocale(saved)},[]);
 const changeLocale=(next:DeskLocale)=>{setLocale(next);localStorage.setItem("mlt-operations-locale",next)};
 const notify=useCallback((next:number)=>{if(next<=unreadRef.current)return;try{const context=new AudioContext();const oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.value=620;gain.gain.value=.04;oscillator.connect(gain);gain.connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.16);}catch{}if(Notification.permission==="granted")new Notification("MLT Chat",{body:t.newMessage});},[t.newMessage]);
 const load=useCallback(async(id=selected)=>{try{const next=await chatApi("operator_sync",id?{conversationId:id}:{});notify(next.unread);unreadRef.current=next.unread;setData(next);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Chat unavailable")}},[selected,notify]);
 useEffect(()=>{load();const timer=window.setInterval(()=>load(),3000);return()=>window.clearInterval(timer)},[load]);
 useEffect(()=>{if(listRef.current)listRef.current.scrollTop=listRef.current.scrollHeight},[data?.messages.length,selected]);
 useEffect(()=>{const restore=()=>{const id=Number(new URLSearchParams(location.search).get("conversation")||0);setSelected(id);load(id)};addEventListener("popstate",restore);return()=>removeEventListener("popstate",restore)},[load]);
 const choose=(id:number)=>{const url=new URL(location.href);url.searchParams.set("conversation",String(id));history.pushState({},"",url);setSelected(id);load(id)};
 const send=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget,message=new FormData(form).get("message");setSending(true);try{const next=await chatApi("operator_send",{conversationId:selected,message});setData(next);form.reset();}catch(reason){setError(reason instanceof Error?reason.message:"Could not send")}finally{setSending(false)}};
 if(error&&!data)return <main className="chat-desk-gate"><section><img src="/mlt-logo.svg?v=20261006-vector" alt="MLT"/><h1>{t.restricted}</h1><p>{error}</p><a href="/account/">{t.signin}</a></section></main>;
 if(!data)return <main className="concierge-loading"/>;
 if(requiredRole&&data.operator.role!==requiredRole)return <main className="chat-desk-gate"><section><img src="/mlt-logo.svg?v=20261006-vector" alt="MLT"/><h1>{t.restricted}</h1><p>This panel is reserved for the {requiredRole} role.</p><a href={data.operator.role==="admin"?"/admin/overview/":"/manager/chat/"}>Open your panel →</a></section></main>;
 const shown=data.conversations.filter(item=>`${item.name} ${item.email}`.toLowerCase().includes(search.toLowerCase()));
 return <main className="chat-desk">
  <header className="chat-desk-top"><a href={data.operator.role==="manager"?"/manager/":"/admin/overview/"}><img src="/mlt-logo.svg?v=20261006-vector" alt="MLT"/></a><div><span className="chat-live-dot"/>{t.live}</div><nav><a href={data.operator.role==="manager"?"/manager/":"/admin/overview/"}>{data.operator.role==="manager"?t.home:t.admin}</a><div className="chat-desk-languages" aria-label="Language">{(["en","de","ru"] as DeskLocale[]).map(item=><button key={item} className={locale===item?"active":""} onClick={()=>changeLocale(item)}>{item.toUpperCase()}</button>)}</div><button onClick={()=>Notification.requestPermission()}>{t.notifications}</button><button onClick={()=>{localStorage.removeItem("mlt-account-token");location.assign("/account/")}}>{t.logout}</button></nav></header>
  <section className="chat-desk-body"><aside className="chat-client-list"><header><p>{t.support}</p><h1>{t.messages} <b>{data.unread}</b></h1><input value={search} onChange={event=>setSearch(event.target.value)} placeholder={t.search}/></header><div>{shown.map(item=><button key={item.id} className={selected===item.id?"active":""} onClick={()=>choose(item.id)}><span>{item.name.split(" ").map(part=>part[0]).slice(0,2).join("")}</span><div><strong>{item.name}</strong><p>{item.last_message}</p><time>{new Date(item.last_message_at.replace(" ","T")).toLocaleString(locale,{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}</time></div>{Number(item.unread_operator)>0&&<b>{item.unread_operator}</b>}</button>)}</div></aside>
  <section className="chat-thread">{data.conversation?<><header><div><small>{t.client}</small><h2>{data.conversation.name}</h2><a href={`mailto:${data.conversation.email}`}>{data.conversation.email}</a></div><span>{data.conversation.locale.toUpperCase()} · {data.conversation.status}</span></header><div className="chat-thread-messages" ref={listRef}>{data.messages.map(message=><article key={message.id} className={message.sender_type}><div><strong>{message.sender_name}</strong><time>{new Date(message.created_at.replace(" ","T")).toLocaleString(locale)}</time></div><p>{message.body}</p></article>)}</div><form onSubmit={send}><textarea required name="message" maxLength={4000} placeholder={t.reply}/><button disabled={sending}>{sending?t.sending:t.send}</button></form></>:<div className="chat-thread-empty"><span>✦</span><h2>{t.select}</h2><p>{t.automatic}</p></div>}</section></section>
 </main>;
}
