import type { Locale } from "./i18n";

type DetailCopy = { manifesto: string; ideal: string; signature: string[]; flow: { label: string; title: string; copy: string }[]; cta: string; back: string; includes: string; itinerary: string; };

export const collectionDetails: Record<string, Record<Locale, DetailCopy>> = {
  freedom: {
    en: { manifesto: "For those who want the keys, the horizon and the freedom to decide what happens next.", ideal: "Independent travellers who value exceptional equipment and thoughtful guidance without a fixed itinerary.", signature: ["Luxury motorhome selected for your party", "Curated MLT map of remarkable places", "Digital route recommendations", "Pre-departure concierge briefing"], itinerary: "Your rhythm", includes: "What shapes the journey", cta: "Begin a Freedom journey", back: "All collections", flow: [{ label: "Day 01", title: "Collect & settle in", copy: "A private handover and complete vehicle introduction." }, { label: "Your days", title: "Follow what moves you", copy: "Use the MLT map or change direction whenever you wish." }, { label: "Always", title: "Recommendations nearby", copy: "Thoughtful places and roads remain close at hand." }] },
    de: { manifesto: "Für alle, die den Schlüssel, den Horizont und die Freiheit möchten, selbst über den nächsten Moment zu entscheiden.", ideal: "Für unabhängige Reisende, die außergewöhnliche Ausstattung und sorgfältige Empfehlungen ohne feste Route schätzen.", signature: ["Passendes Luxus-Reisemobil", "Kuratierte MLT Karte besonderer Orte", "Digitale Routenempfehlungen", "Persönliches Briefing vor Abreise"], itinerary: "Ihr Rhythmus", includes: "Was die Reise prägt", cta: "Freedom Reise beginnen", back: "Alle Kollektionen", flow: [{ label: "Tag 01", title: "Übernahme & Ankommen", copy: "Private Übergabe und ausführliche Fahrzeugeinweisung." }, { label: "Ihre Tage", title: "Folgen Sie Ihrer Neugier", copy: "Nutzen Sie die MLT Karte oder ändern Sie jederzeit die Richtung." }, { label: "Jederzeit", title: "Empfehlungen in Ihrer Nähe", copy: "Besondere Orte und Straßen bleiben immer griffbereit." }] },
  },
  signature: {
    en: { manifesto: "A beautifully resolved road journey, prepared around your tastes before the first mile begins.", ideal: "Travellers who want independence on the road with every important detail already considered.", signature: ["A personal route designed around you", "Reserved premium campsites", "The finest panoramic roads", "Restaurants, culture and private activities"], itinerary: "A composed journey", includes: "Prepared around you", cta: "Request a Signature proposal", back: "All collections", flow: [{ label: "Before", title: "Private consultation", copy: "We learn your pace, interests and preferred landscapes." }, { label: "The route", title: "Every detail resolved", copy: "Stays, roads and experiences are woven into one itinerary." }, { label: "Departure", title: "Simply take the wheel", copy: "Everything essential is ready when your journey begins." }] },
    de: { manifesto: "Eine bis ins Detail komponierte Straßenreise, abgestimmt auf Ihre Wünsche — noch bevor der erste Kilometer beginnt.", ideal: "Für Reisende, die unterwegs unabhängig bleiben möchten, während alle wichtigen Details bereits vorbereitet sind.", signature: ["Persönlich entworfene Route", "Reservierte Premium-Stellplätze", "Die schönsten Panoramastraßen", "Restaurants, Kultur und private Aktivitäten"], itinerary: "Eine komponierte Reise", includes: "Für Sie vorbereitet", cta: "Signature Angebot anfragen", back: "Alle Kollektionen", flow: [{ label: "Vorher", title: "Privates Gespräch", copy: "Wir lernen Ihr Tempo, Ihre Interessen und bevorzugten Landschaften kennen." }, { label: "Die Route", title: "Jedes Detail geklärt", copy: "Aufenthalte, Straßen und Erlebnisse werden zu einer Reise verbunden." }, { label: "Abreise", title: "Einfach losfahren", copy: "Alles Wesentliche ist vorbereitet, wenn Ihre Reise beginnt." }] },
  },
  concierge: {
    en: { manifesto: "The freedom of the open road, supported every hour by someone who already knows the next best move.", ideal: "Guests who want to remain spontaneous while a dedicated concierge handles every change and request.", signature: ["24/7 online concierge", "Live itinerary changes", "Restaurant and excursion reservations", "Vehicle service and emergency support"], itinerary: "Freedom, supported", includes: "With you, around the clock", cta: "Meet your Concierge", back: "All collections", flow: [{ label: "24 / 7", title: "One message away", copy: "Your dedicated contact remains available throughout the journey." }, { label: "In motion", title: "Plans can change", copy: "Routes and reservations adapt as your wishes evolve." }, { label: "If needed", title: "Assistance, quietly handled", copy: "Technical and emergency support is coordinated for you." }] },
    de: { manifesto: "Die Freiheit der offenen Straße — zu jeder Stunde begleitet von jemandem, der den nächsten besten Schritt kennt.", ideal: "Für Gäste, die spontan bleiben möchten, während ein persönlicher Concierge Änderungen und Wünsche organisiert.", signature: ["Online-Concierge rund um die Uhr", "Flexible Routenänderungen", "Restaurant- und Ausflugsreservierungen", "Fahrzeugservice und Notfallhilfe"], itinerary: "Freiheit mit Rückhalt", includes: "Rund um die Uhr bei Ihnen", cta: "Concierge kennenlernen", back: "Alle Kollektionen", flow: [{ label: "24 / 7", title: "Nur eine Nachricht entfernt", copy: "Ihre persönliche Kontaktperson bleibt während der gesamten Reise erreichbar." }, { label: "Unterwegs", title: "Pläne dürfen sich ändern", copy: "Route und Reservierungen passen sich Ihren Wünschen an." }, { label: "Bei Bedarf", title: "Diskrete Unterstützung", copy: "Technische Hilfe und Notfälle werden für Sie koordiniert." }] },
  },
  private: {
    en: { manifesto: "A private travelling residence with an exceptional team, created for guests who expect nothing to be ordinary.", ideal: "Families, principals and private groups seeking complete service, privacy and rare access across Europe.", signature: ["Individual route and private driver", "Technician, chef and service staff", "Half board and private excursions", "VIP transfers and full concierge"], itinerary: "A world of your own", includes: "Your private travelling team", cta: "Discuss a Private expedition", back: "All collections", flow: [{ label: "Your team", title: "Service travels with you", copy: "Driver, technician and hospitality staff move as one discreet unit." }, { label: "Each day", title: "Created around your party", copy: "Dining, excursions and timing are entirely personal." }, { label: "Throughout", title: "Privacy without compromise", copy: "Every transition is managed with quiet precision." }] },
    de: { manifesto: "Eine private Residenz auf Reisen mit außergewöhnlichem Team — für Gäste, die nichts Gewöhnliches erwarten.", ideal: "Für Familien, Persönlichkeiten und private Gruppen, die vollständigen Service, Privatsphäre und seltene Zugänge suchen.", signature: ["Individuelle Route und Privatfahrer", "Techniker, Koch und Servicepersonal", "Halbpension und private Ausflüge", "VIP-Transfers und vollständiger Concierge"], itinerary: "Eine Welt für sich", includes: "Ihr privates Reiseteam", cta: "Private Expedition besprechen", back: "Alle Kollektionen", flow: [{ label: "Ihr Team", title: "Service reist mit", copy: "Fahrer, Techniker und Hospitality-Team agieren als diskrete Einheit." }, { label: "Jeder Tag", title: "Für Ihre Gruppe gestaltet", copy: "Kulinarik, Ausflüge und Zeitplan sind vollständig persönlich." }, { label: "Durchgehend", title: "Privatsphäre ohne Kompromisse", copy: "Jeder Übergang wird mit ruhiger Präzision organisiert." }] },
  },
};
