import type { Locale } from "./i18n";

type DetailCopy = { manifesto: string; ideal: string; signature: string[]; flow: { label: string; title: string; copy: string }[]; cta: string; back: string; includes: string; itinerary: string; };

export const collectionDetails: Record<string, Record<Locale, DetailCopy>> = {
  freedom: {
    en: { manifesto: "For those who want the keys, the horizon and the freedom to decide what happens next.", ideal: "Independent travellers who value exceptional equipment and thoughtful guidance without a fixed itinerary.", signature: ["Luxury motorhome selected for your party", "Curated MLT map of remarkable places", "Digital route recommendations", "Pre-departure concierge briefing"], itinerary: "Your rhythm", includes: "What shapes the journey", cta: "Begin a Freedom journey", back: "All collections", flow: [{ label: "Day 01", title: "Collect & settle in", copy: "A private handover and complete vehicle introduction." }, { label: "Your days", title: "Follow what moves you", copy: "Use the MLT map or change direction whenever you wish." }, { label: "Always", title: "Recommendations nearby", copy: "Thoughtful places and roads remain close at hand." }] },
    de: { manifesto: "Für alle, die den Schlüssel, den Horizont und die Freiheit möchten, selbst über den nächsten Moment zu entscheiden.", ideal: "Für unabhängige Reisende, die außergewöhnliche Ausstattung und sorgfältige Empfehlungen ohne feste Route schätzen.", signature: ["Passendes Luxus-Reisemobil", "Kuratierte MLT Karte besonderer Orte", "Digitale Routenempfehlungen", "Persönliches Briefing vor Abreise"], itinerary: "Ihr Rhythmus", includes: "Was die Reise prägt", cta: "Freedom Reise beginnen", back: "Alle Kollektionen", flow: [{ label: "Tag 01", title: "Übernahme & Ankommen", copy: "Private Übergabe und ausführliche Fahrzeugeinweisung." }, { label: "Ihre Tage", title: "Folgen Sie Ihrer Neugier", copy: "Nutzen Sie die MLT Karte oder ändern Sie jederzeit die Richtung." }, { label: "Jederzeit", title: "Empfehlungen in Ihrer Nähe", copy: "Besondere Orte und Straßen bleiben immer griffbereit." }] },
    ru: { manifesto: "Для тех, кто хочет сам решать, что будет дальше.", ideal: "Для независимых путешественников, которые ценят особенное оснащение и продуманные рекомендации без жёсткого маршрута.", signature: ["Люксовый автодом", "Курированная карта MLT", "Цифровые рекомендации", "Личный брифинг"], itinerary: "Ваш ритм", includes: "Что формирует путешествие", cta: "Начать Freedom", back: "Все коллекции", flow: [{ label: "День 01", title: "Получение и знакомство", copy: "Личная передача и полное знакомство с автодомом." }, { label: "Ваши дни", title: "Следуйте за интересом", copy: "Пользуйтесь картой MLT или меняйте направление." }, { label: "Всегда", title: "Рекомендации рядом", copy: "Особенные места и дороги всегда под рукой." }] },
  },
  signature: {
    en: { manifesto: "A beautifully resolved road journey, prepared around your tastes before the first mile begins.", ideal: "Travellers who want independence on the road with every important detail already considered.", signature: ["A personal route designed around you", "Reserved premium campsites", "The finest panoramic roads", "Restaurants, culture and private activities"], itinerary: "A composed journey", includes: "Prepared around you", cta: "Request a Signature proposal", back: "All collections", flow: [{ label: "Before", title: "Private consultation", copy: "We learn your pace, interests and preferred landscapes." }, { label: "The route", title: "Every detail resolved", copy: "Stays, roads and experiences are woven into one itinerary." }, { label: "Departure", title: "Simply take the wheel", copy: "Everything essential is ready when your journey begins." }] },
    de: { manifesto: "Eine bis ins Detail komponierte Straßenreise, abgestimmt auf Ihre Wünsche — noch bevor der erste Kilometer beginnt.", ideal: "Für Reisende, die unterwegs unabhängig bleiben möchten, während alle wichtigen Details bereits vorbereitet sind.", signature: ["Persönlich entworfene Route", "Reservierte Premium-Stellplätze", "Die schönsten Panoramastraßen", "Restaurants, Kultur und private Aktivitäten"], itinerary: "Eine komponierte Reise", includes: "Für Sie vorbereitet", cta: "Signature Angebot anfragen", back: "Alle Kollektionen", flow: [{ label: "Vorher", title: "Privates Gespräch", copy: "Wir lernen Ihr Tempo, Ihre Interessen und bevorzugten Landschaften kennen." }, { label: "Die Route", title: "Jedes Detail geklärt", copy: "Aufenthalte, Straßen und Erlebnisse werden zu einer Reise verbunden." }, { label: "Abreise", title: "Einfach losfahren", copy: "Alles Wesentliche ist vorbereitet, wenn Ihre Reise beginnt." }] },
    ru: { manifesto: "Дорожное путешествие, продуманное до мелочей вокруг ваших вкусов.", ideal: "Для тех, кто хочет сохранить независимость, зная, что все важные детали уже учтены.", signature: ["Личный маршрут", "Забронированные премиальные стоянки", "Лучшие панорамные дороги", "Рестораны, культура и частные впечатления"], itinerary: "Продуманное путешествие", includes: "Всё подготовлено для вас", cta: "Получить Signature-предложение", back: "Все коллекции", flow: [{ label: "До поездки", title: "Личная консультация", copy: "Мы узнаем ваш темп, интересы и любимые ландшафты." }, { label: "Маршрут", title: "Каждая деталь решена", copy: "Стоянки, дороги и впечатления соединены в одну историю." }, { label: "Отправление", title: "Просто садитесь за руль", copy: "Всё важное уже готово к началу путешествия." }] },
  },
  concierge: {
    en: { manifesto: "The freedom of the open road, supported every hour by someone who already knows the next best move.", ideal: "Guests who want to remain spontaneous while a dedicated concierge handles every change and request.", signature: ["24/7 online concierge", "Live itinerary changes", "Restaurant and excursion reservations", "Vehicle service and emergency support"], itinerary: "Freedom, supported", includes: "With you, around the clock", cta: "Meet your Concierge", back: "All collections", flow: [{ label: "24 / 7", title: "One message away", copy: "Your dedicated contact remains available throughout the journey." }, { label: "In motion", title: "Plans can change", copy: "Routes and reservations adapt as your wishes evolve." }, { label: "If needed", title: "Assistance, quietly handled", copy: "Technical and emergency support is coordinated for you." }] },
    de: { manifesto: "Die Freiheit der offenen Straße — zu jeder Stunde begleitet von jemandem, der den nächsten besten Schritt kennt.", ideal: "Für Gäste, die spontan bleiben möchten, während ein persönlicher Concierge Änderungen und Wünsche organisiert.", signature: ["Online-Concierge rund um die Uhr", "Flexible Routenänderungen", "Restaurant- und Ausflugsreservierungen", "Fahrzeugservice und Notfallhilfe"], itinerary: "Freiheit mit Rückhalt", includes: "Rund um die Uhr bei Ihnen", cta: "Concierge kennenlernen", back: "Alle Kollektionen", flow: [{ label: "24 / 7", title: "Nur eine Nachricht entfernt", copy: "Ihre persönliche Kontaktperson bleibt während der gesamten Reise erreichbar." }, { label: "Unterwegs", title: "Pläne dürfen sich ändern", copy: "Route und Reservierungen passen sich Ihren Wünschen an." }, { label: "Bei Bedarf", title: "Diskrete Unterstützung", copy: "Technische Hilfe und Notfälle werden für Sie koordiniert." }] },
    ru: { manifesto: "Свобода открытой дороги с поддержкой человека, который всегда знает лучший следующий шаг.", ideal: "Для гостей, которые хотят оставаться спонтанными, пока личный консьерж решает все вопросы.", signature: ["Онлайн-консьерж 24/7", "Изменения маршрута", "Бронирование ресторанов и экскурсий", "Техническая и экстренная помощь"], itinerary: "Свобода с поддержкой", includes: "Рядом круглосуточно", cta: "Познакомиться с консьержем", back: "Все коллекции", flow: [{ label: "24 / 7", title: "Всегда на связи", copy: "Ваш личный контакт доступен всю поездку." }, { label: "В пути", title: "Планы могут меняться", copy: "Маршрут и бронирования подстраиваются под ваши желания." }, { label: "При необходимости", title: "Незаметная помощь", copy: "Мы координируем техническую и экстренную помощь." }] },
  },
  private: {
    en: { manifesto: "A private travelling residence with an exceptional team, created for guests who expect nothing to be ordinary.", ideal: "Families, principals and private groups seeking complete service, privacy and rare access across Europe.", signature: ["Individual route and private driver", "Technician, chef and service staff", "Half board and private excursions", "VIP transfers and full concierge"], itinerary: "A world of your own", includes: "Your private travelling team", cta: "Discuss a Private expedition", back: "All collections", flow: [{ label: "Your team", title: "Service travels with you", copy: "Driver, technician and hospitality staff move as one discreet unit." }, { label: "Each day", title: "Created around your party", copy: "Dining, excursions and timing are entirely personal." }, { label: "Throughout", title: "Privacy without compromise", copy: "Every transition is managed with quiet precision." }] },
    de: { manifesto: "Eine private Residenz auf Reisen mit außergewöhnlichem Team — für Gäste, die nichts Gewöhnliches erwarten.", ideal: "Für Familien, Persönlichkeiten und private Gruppen, die vollständigen Service, Privatsphäre und seltene Zugänge suchen.", signature: ["Individuelle Route und Privatfahrer", "Techniker, Koch und Servicepersonal", "Halbpension und private Ausflüge", "VIP-Transfers und vollständiger Concierge"], itinerary: "Eine Welt für sich", includes: "Ihr privates Reiseteam", cta: "Private Expedition besprechen", back: "Alle Kollektionen", flow: [{ label: "Ihr Team", title: "Service reist mit", copy: "Fahrer, Techniker und Hospitality-Team agieren als diskrete Einheit." }, { label: "Jeder Tag", title: "Für Ihre Gruppe gestaltet", copy: "Kulinarik, Ausflüge und Zeitplan sind vollständig persönlich." }, { label: "Durchgehend", title: "Privatsphäre ohne Kompromisse", copy: "Jeder Übergang wird mit ruhiger Präzision organisiert." }] },
    ru: { manifesto: "Частная резиденция в пути с исключительной командой для тех, кто не приемлет обычного.", ideal: "Для семей и частных групп, которым нужны полный сервис, приватность и редкие возможности.", signature: ["Личный маршрут и водитель", "Техник, повар и сервисная команда", "Полупансион и частные экскурсии", "VIP-трансферы и полный консьерж-сервис"], itinerary: "Ваш личный мир", includes: "Ваша личная команда", cta: "Обсудить Private-экспедицию", back: "Все коллекции", flow: [{ label: "Ваша команда", title: "Сервис путешествует с вами", copy: "Водитель, техник и hospitality-команда работают как единое целое." }, { label: "Каждый день", title: "Создано для вашей группы", copy: "Питание, экскурсии и расписание полностью персональны." }, { label: "Всю поездку", title: "Приватность без компромиссов", copy: "Каждый переход организован с точностью и тактом." }] },
  },
  proposal: {
    en: { manifesto: "The art of saying yes at the edge of the world.", ideal: "A complete proposal abroad without the search for photographers, decorators, locations or unfamiliar logistics. Choose the destination and the ring; MLT handles everything else.", signature: ["Premium Basic or Premium-class motorhome for 3–7 days", "A precisely selected private European location", "Dedicated 24/7 proposal concierge", "Complete route and on-site coordination"], itinerary: "Your turnkey proposal", includes: "The essential package", cta: "Create our Proposal journey", back: "All collections", flow: [{ label: "Visual & Memory", title: "A moment beautifully preserved", copy: "A discreet photographer, cinematic film and optional aerial drone coverage." }, { label: "Aesthetics & Gastronomy", title: "Every detail sets the scene", copy: "Floral design, candlelight, champagne, local delicacies and a private chef or panoramic restaurant." }, { label: "Logistics & Wow", title: "An unforgettable arrival", copy: "Helicopter transfer, a classic car or electric transport for the journey after the answer." }] },
    de: { manifesto: "Die Kunst, am Ende der Welt Ja zu sagen.", ideal: "Ein vollständig organisiertes Heiratsversprechen im Ausland — ohne Fotografen, Dekoration, Orte oder Logistik selbst koordinieren zu müssen. Sie wählen das Ziel und den Ring; MLT übernimmt alles Weitere.", signature: ["Premium-Reisemobil der Basic- oder Premium-Kategorie für 3–7 Tage", "Präzise ausgewählter privater Ort in Europa", "Persönlicher Proposal-Concierge rund um die Uhr", "Vollständige Route und Koordination vor Ort"], itinerary: "Ihr Antrag aus einer Hand", includes: "Das Basispaket", cta: "Proposal Reise gestalten", back: "Alle Kollektionen", flow: [{ label: "Visual & Memory", title: "Ein Moment, wunderschön bewahrt", copy: "Diskreter Fotograf, filmische Begleitung und optional Luftaufnahmen mit der Drohne." }, { label: "Atmosphäre & Kulinarik", title: "Jedes Detail schafft die Szene", copy: "Floristik, Kerzenlicht, Champagner, lokale Spezialitäten und privater Koch oder Panoramarestaurant." }, { label: "Logistik & Wow", title: "Ein unvergesslicher Auftritt", copy: "Helikoptertransfer, Oldtimer oder elektrischer Transport für den Weg nach dem Ja." }] },
    ru: { manifesto: "Искусство сказать «да» на краю света.", ideal: "Полностью организованное предложение за рубежом. Вы выбираете место и кольцо, MLT берёт на себя всё остальное.", signature: ["Премиальный автодом на 3–7 дней", "Точно подобранная частная локация в Европе", "Личный консьерж 24/7", "Маршрут и координация на месте"], itinerary: "Предложение под ключ", includes: "Основной пакет", cta: "Создать Proposal-путешествие", back: "Все коллекции", flow: [{ label: "Визуальная история", title: "Момент, сохранённый навсегда", copy: "Незаметный фотограф, кинематографичное видео и съёмка с дрона." }, { label: "Атмосфера и гастрономия", title: "Каждая деталь создаёт сцену", copy: "Флористика, свечи, шампанское, местные деликатесы и частный повар." }, { label: "Логистика и вау-эффект", title: "Незабываемое появление", copy: "Трансфер на вертолёте, ретроавтомобиль или электротранспорт." }] },
  },
};
