import type { Locale } from "./i18n";

type FleetCopy = { tagline: string; intro: string; highlights: string[]; spaces: { title: string; copy: string }[]; suited: string[]; labels: { back: string; guests: string; transmission: string; length: string; from: string; highlights: string; spaces: string; suited: string; request: string; concept: string } };

export const fleetDetails: Record<string, Record<Locale, FleetCopy>> = {
  explorer: {
    en: { tagline: "Long roads, entirely your own.", intro: "A confident grand tourer balancing generous living space with the freedom to move through mountain roads and historic towns.", highlights: ["Panoramic front lounge", "Private rear sleeping suite", "Full kitchen and climate control", "Extended off-grid capability", "MLT navigation and route kit", "Premium outdoor living set"], spaces: [{ title: "The lounge", copy: "A light-filled place to slow down, dine and watch the landscape change." }, { title: "The private suite", copy: "A calm sleeping space designed for restorative nights on the road." }, { title: "Outdoor living", copy: "Everything needed to make a lake, vineyard or mountain view feel like home." }], suited: ["Freedom Collection", "Signature Collection"], labels: { back: "Back to fleet", guests: "Guests", transmission: "Transmission", length: "Length", from: "From", highlights: "Key equipment", spaces: "Life on board", suited: "Available with", request: "Request this motorhome", concept: "Concept specifications for demonstration" } },
    de: { tagline: "Lange Straßen, ganz für Sie.", intro: "Ein souveräner Grand Tourer, der großzügigen Wohnraum mit der Freiheit verbindet, Bergstraßen und historische Orte mühelos zu entdecken.", highlights: ["Panorama-Frontlounge", "Privater Schlafbereich im Heck", "Vollständige Küche und Klimatisierung", "Erweiterte autarke Versorgung", "MLT Navigation und Routenset", "Premium-Outdoor-Ausstattung"], spaces: [{ title: "Die Lounge", copy: "Ein lichtdurchfluteter Ort zum Ankommen, Essen und Beobachten der Landschaft." }, { title: "Die private Suite", copy: "Ein ruhiger Schlafbereich für erholsame Nächte unterwegs." }, { title: "Leben im Freien", copy: "Alles, damit See, Weinberg oder Bergpanorama sich wie Zuhause anfühlen." }], suited: ["Freedom Collection", "Signature Collection"], labels: { back: "Zurück zur Flotte", guests: "Gäste", transmission: "Getriebe", length: "Länge", from: "Ab", highlights: "Ausstattung", spaces: "Leben an Bord", suited: "Verfügbar mit", request: "Dieses Reisemobil anfragen", concept: "Konzeptdaten für die Demonstration" } },
  },
  granduca: {
    en: { tagline: "A private residence in motion.", intro: "The flagship MLT experience: expansive, serene and designed for guests who want the road without leaving the feeling of a private residence behind.", highlights: ["Full-width panoramic lounge", "Separate master suite", "Chef-ready kitchen", "Luxury bathroom and wardrobe", "Advanced climate and energy system", "Integrated concierge connectivity"], spaces: [{ title: "The residence", copy: "Generous proportions, refined materials and uninterrupted views create a genuine travelling home." }, { title: "The master suite", copy: "A separated private space with considered storage, lighting and quiet." }, { title: "Hosted dining", copy: "A kitchen and dining setting prepared for private chef service on the road." }], suited: ["Signature Collection", "Concierge Collection", "Private Collection"], labels: { back: "Back to fleet", guests: "Guests", transmission: "Transmission", length: "Length", from: "From", highlights: "Key equipment", spaces: "Life on board", suited: "Available with", request: "Request the Granduca", concept: "Concept specifications for demonstration" } },
    de: { tagline: "Eine private Residenz in Bewegung.", intro: "Das Flaggschiff von MLT: großzügig, ruhig und für Gäste gestaltet, die unterwegs nicht auf das Gefühl einer privaten Residenz verzichten möchten.", highlights: ["Panorama-Lounge über volle Breite", "Separate Master-Suite", "Küche für privaten Kochservice", "Luxusbad und Garderobe", "Fortschrittliches Klima- und Energiesystem", "Integrierte Concierge-Verbindung"], spaces: [{ title: "Die Residenz", copy: "Großzügige Proportionen, hochwertige Materialien und freie Ausblicke schaffen ein echtes Zuhause auf Reisen." }, { title: "Die Master-Suite", copy: "Ein separater privater Bereich mit durchdachtem Stauraum, Licht und Ruhe." }, { title: "Privates Dining", copy: "Küche und Essbereich sind für den Service eines privaten Kochs vorbereitet." }], suited: ["Signature Collection", "Concierge Collection", "Private Collection"], labels: { back: "Zurück zur Flotte", guests: "Gäste", transmission: "Getriebe", length: "Länge", from: "Ab", highlights: "Ausstattung", spaces: "Leben an Bord", suited: "Verfügbar mit", request: "Granduca anfragen", concept: "Konzeptdaten für die Demonstration" } },
  },
  compatto: {
    en: { tagline: "Small footprint. Expansive freedom.", intro: "An agile luxury tourer for two, equally at ease beside an alpine lake or moving through the narrow streets of a historic European town.", highlights: ["Flexible lounge for two", "Premium convertible sleeping area", "Compact full kitchen", "Integrated shower and washroom", "Efficient off-grid system", "City and alpine driving package"], spaces: [{ title: "The flexible lounge", copy: "A compact interior that changes naturally from daytime living to a restful night." }, { title: "Everything considered", copy: "Kitchen, storage and washroom are composed around effortless use." }, { title: "Closer to the place", copy: "Compact proportions unlock roads and destinations beyond larger touring vehicles." }], suited: ["Freedom Collection", "Signature Collection"], labels: { back: "Back to fleet", guests: "Guests", transmission: "Transmission", length: "Length", from: "From", highlights: "Key equipment", spaces: "Life on board", suited: "Available with", request: "Request the Compatto", concept: "Concept specifications for demonstration" } },
    de: { tagline: "Kompakt im Format. Groß in der Freiheit.", intro: "Ein wendiger Luxus-Tourer für zwei — ebenso selbstverständlich am Alpensee wie in den engen Straßen einer historischen europäischen Stadt.", highlights: ["Flexible Lounge für zwei", "Hochwertiger wandelbarer Schlafbereich", "Kompakte vollwertige Küche", "Integrierte Dusche und Waschraum", "Effizientes autarkes System", "Stadt- und Alpen-Fahrpaket"], spaces: [{ title: "Die flexible Lounge", copy: "Ein kompakter Innenraum, der sich selbstverständlich vom Wohnbereich zum Schlafplatz verwandelt." }, { title: "Alles durchdacht", copy: "Küche, Stauraum und Waschraum sind für mühelose Nutzung komponiert." }, { title: "Näher am Reiseziel", copy: "Kompakte Proportionen öffnen Straßen und Orte jenseits größerer Reisemobile." }], suited: ["Freedom Collection", "Signature Collection"], labels: { back: "Zurück zur Flotte", guests: "Gäste", transmission: "Getriebe", length: "Länge", from: "Ab", highlights: "Ausstattung", spaces: "Leben an Bord", suited: "Verfügbar mit", request: "Compatto anfragen", concept: "Konzeptdaten für die Demonstration" } },
  },
};
