export type Locale = "en" | "de";

export const translations = {
  en: {
    collections: "Collections", fleet: "Fleet", smartMap: "Smart map", experiences: "Experiences", journeyDesigner: "Journey designer", concierge: "Talk to a concierge",
    kicker: "Individual road expeditions", heroLine1: "Europe,", heroLine2: "without limits.", heroCopy: "Not a rental. A private way of moving through the world — composed around you.", discover: "Discover the collections", film: "Watch the film",
    begin: "Begin your journey", plan: "Plan an expedition", startingCountry: "Starting country", arrival: "Arrival", departure: "Departure", travellers: "Travellers", availability: "Explore availability",
    nowExploring: "Now exploring", firstDepartures: "First departures", september: "September 2026", philosophy: "The MLT philosophy", notRent: "We do not rent", motorhomes: "motorhomes.", freedomLead: "We create the freedom to wake up somewhere", extraordinary: "extraordinary.", philosophyCopy: "Every MLT expedition is a considered balance of remarkable roads, rare places and effortless service — from total independence to a fully hosted private journey.",
    privateFleet: "The private fleet", chooseHow: "Choose how", youMove: "you move.", fleetCopy: "Exceptionally equipped motorhomes selected for long-distance comfort, privacy and complete independence.", discoverMotorhome: "Discover this motorhome",
    ways: "Four ways to travel", chooseYour: "Choose your", collection: "collection.", collectionCopy: "Each collection begins with the same promise: the finest motorhomes, a remarkable European landscape and the space to travel differently.", duration: "Duration", from: "From",
    places: "Places worth", changing: "changing course for.", mapCopy: "Explore a first edit of remarkable roads, private stays and rare experiences. Select what moves you — our concierge will compose the journey between them.", selectedRoute: "Your selected route", selectedPlaces: "places", suggestedDuration: "Suggested duration", buildRoute: "Build this route with a concierge",
    beyond: "Beyond the road", additional: "Additional", experienceWord: "experiences.", experienceCopy: "Rare access, remarkable people and private moments — selected to become part of your route whenever you wish.", askConcierge: "Ask your concierge",
    assembled: "Your journey, assembled", buildChapter: "Build the first chapter", expedition: "of your expedition.", designerCopy: "Select a collection, a landscape and your pace. We will turn the outline into a private itinerary.", selectCollection: "Select your collection", landscape: "Landscape", yourCollection: "Your collection", beginningIn: "Beginning in", indicativeRate: "Indicative rate", continueJourney: "Continue your journey",
    conversation: "A private conversation", someJourneys: "Some journeys begin", yours: "Yours begins here.", speak: "Speak with our concierge",
    privateRequest: "Your private request", compose: "Let us compose", theJourney: "the journey.", modalCopy: "Share a few details. An MLT concierge will return with a considered first proposal.", expeditionOutline: "Expedition outline", firstName: "First name", lastName: "Last name", email: "Email", phone: "Phone", preferred: "Preferred contact", bestTime: "Best time to reach you", exceptional: "What would make this journey exceptional?", consent: "I agree that MLT may use these details to prepare and discuss my travel proposal.", requestProposal: "Request my private proposal", sending: "Sending securely...", noCommitment: "Your information remains private. No payment or commitment is required.", received: "Request received", thankYou: "Thank you.", begun: "Your journey has begun.", successCopy: "An MLT concierge will review your preferences and contact you within one business day with the next private step.", returnMlt: "Return to MLT",
  },
  de: {
    collections: "Kollektionen", fleet: "Flotte", smartMap: "Smart Map", experiences: "Erlebnisse", journeyDesigner: "Reiseplaner", concierge: "Concierge kontaktieren",
    kicker: "Individuelle Straßenexpeditionen", heroLine1: "Europa,", heroLine2: "ohne Grenzen.", heroCopy: "Keine Vermietung. Eine private Art, die Welt zu bereisen — persönlich für Sie komponiert.", discover: "Kollektionen entdecken", film: "Film ansehen",
    begin: "Ihre Reise beginnt", plan: "Expedition planen", startingCountry: "Startland", arrival: "Anreise", departure: "Abreise", travellers: "Reisende", availability: "Verfügbarkeit prüfen",
    nowExploring: "Aktuelle Reiseziele", firstDepartures: "Erste Abreisen", september: "September 2026", philosophy: "Die MLT Philosophie", notRent: "Wir vermieten keine", motorhomes: "Wohnmobile.", freedomLead: "Wir schaffen die Freiheit, an einem", extraordinary: "außergewöhnlichen Ort aufzuwachen.", philosophyCopy: "Jede MLT Expedition verbindet außergewöhnliche Straßen, seltene Orte und mühelosen Service — von völliger Unabhängigkeit bis zur vollständig begleiteten Privatreise.",
    privateFleet: "Die private Flotte", chooseHow: "Wählen Sie, wie", youMove: "Sie reisen.", fleetCopy: "Außergewöhnlich ausgestattete Reisemobile für Langstreckenkomfort, Privatsphäre und vollständige Unabhängigkeit.", discoverMotorhome: "Reisemobil entdecken",
    ways: "Vier Arten zu reisen", chooseYour: "Wählen Sie Ihre", collection: "Kollektion.", collectionCopy: "Jede Kollektion beginnt mit demselben Versprechen: exklusive Reisemobile, außergewöhnliche Landschaften und die Freiheit, anders zu reisen.", duration: "Dauer", from: "Ab",
    places: "Orte, für die man", changing: "gerne den Kurs ändert.", mapCopy: "Entdecken Sie besondere Straßen, private Unterkünfte und seltene Erlebnisse. Wählen Sie, was Sie bewegt — unser Concierge komponiert die Reise dazwischen.", selectedRoute: "Ihre ausgewählte Route", selectedPlaces: "Orte", suggestedDuration: "Empfohlene Dauer", buildRoute: "Route mit Concierge planen",
    beyond: "Jenseits der Straße", additional: "Zusätzliche", experienceWord: "Erlebnisse.", experienceCopy: "Seltener Zugang, besondere Menschen und private Momente — jederzeit passend in Ihre Route integriert.", askConcierge: "Concierge fragen",
    assembled: "Ihre Reise, komponiert", buildChapter: "Gestalten Sie das erste Kapitel", expedition: "Ihrer Expedition.", designerCopy: "Wählen Sie Kollektion, Landschaft und Reisetempo. Wir verwandeln den Entwurf in eine private Reiseroute.", selectCollection: "Kollektion auswählen", landscape: "Landschaft", yourCollection: "Ihre Kollektion", beginningIn: "Start in", indicativeRate: "Preisrahmen", continueJourney: "Reise fortsetzen",
    conversation: "Ein privates Gespräch", someJourneys: "Manche Reisen beginnen", yours: "Ihre beginnt hier.", speak: "Mit Concierge sprechen",
    privateRequest: "Ihre private Anfrage", compose: "Lassen Sie uns", theJourney: "Ihre Reise komponieren.", modalCopy: "Teilen Sie uns einige Details mit. Ihr MLT Concierge meldet sich mit einem sorgfältig ausgearbeiteten ersten Vorschlag.", expeditionOutline: "Reiseübersicht", firstName: "Vorname", lastName: "Nachname", email: "E-Mail", phone: "Telefon", preferred: "Bevorzugter Kontakt", bestTime: "Beste Kontaktzeit", exceptional: "Was würde diese Reise außergewöhnlich machen?", consent: "Ich stimme zu, dass MLT diese Angaben zur Vorbereitung und Besprechung meines Reiseangebots verwendet.", requestProposal: "Privates Angebot anfragen", sending: "Wird sicher gesendet...", noCommitment: "Ihre Angaben bleiben vertraulich. Keine Zahlung oder Verpflichtung erforderlich.", received: "Anfrage erhalten", thankYou: "Vielen Dank.", begun: "Ihre Reise hat begonnen.", successCopy: "Ein MLT Concierge prüft Ihre Wünsche und meldet sich innerhalb eines Werktages mit dem nächsten privaten Schritt.", returnMlt: "Zurück zu MLT",
  },
} as const;

export const collectionDe: Record<string, { eyebrow: string; days: string; mode: string; inclusions: string[] }> = {
  freedom: { eyebrow: "Selbstbestimmt entdecken", days: "7–30 Tage", mode: "Unabhängig", inclusions: ["Luxus-Reisemobil", "Kuratierte Karte", "MLT Routen-App", "Lokale Empfehlungen"] },
  signature: { eyebrow: "Von Anfang bis Ende kuratiert", days: "7–14 Tage", mode: "Maßgeschneidert", inclusions: ["Persönliche Route", "Reservierte Stellplätze", "Panoramastraßen", "Restaurants & Aktivitäten"] },
  concierge: { eyebrow: "Immer einen Schritt voraus", days: "7–15 Tage", mode: "24/7 begleitet", inclusions: ["Flexible Routenänderung", "Restaurantreservierungen", "Ausflüge", "Pannenhilfe"] },
  private: { eyebrow: "Die exklusivste Art zu reisen", days: "7–21 Tage", mode: "Vollständig begleitet", inclusions: ["Privatfahrer & Techniker", "Koch & Service", "Halbpension", "VIP-Transfers & Concierge"] },
};
