"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import CollectionCarousel, { scrollCollectionCarouselIntoView } from "../CollectionCarousel";
import RealRouteMap from "../plan/RealRouteMap";
import { mapPoints } from "../../content/mlt";
import MobilePreviewHeader from "./MobilePreviewHeader";
import MobilePreviewFooter from "./MobilePreviewFooter";
import styles from "./home-preview.module.css";

type Locale = "en" | "de" | "ru";
const collections = [
  ["freedom", "Freedom", "/collection-freedom-carousel-v2.jpg", "7–30 days", "From €1,490 for 7 days"],
  ["signature", "Signature", "/collection-signature-carousel-v2.jpg", "7–14 days", "From €2,490 for 7 days"],
  ["concierge", "Concierge", "/collection-concierge-carousel-v2.jpg", "7–14 days", "From €4,990 for 7 days"],
  ["private", "Private", "/collection-private-carousel-v2.jpg", "7–21 days", "From €19,900 for 7 days"],
  ["honeymoon", "Honeymoon", "/collection-honeymoon-carousel-v2.jpg", "7–14 days", "From €5,900 for 7 days"],
] as const;
const experienceImages = ["/concierge-family-dolomites.jpg", "/signature-route-mediterranean.jpg", "/experience-wine-v2.webp", "/route-alpine.jpg"];
const philosophyImages = ["/route-mediterranean.jpg", "/collection-private-carousel-v2.jpg", "/experience-wine-v2.webp"];
const text = {
  en:{hero:"We create moments that stay with you forever – through Europe’s most remarkable landscapes, with every detail considered.",choose:"Choose a collection",philosophy:"The MLT philosophy",freedom:"Freedom, already taken care of.",freedomCopy:"Most companies sell you the freedom to do everything yourself. We create the freedom to simply live the moment. No planning. No stress. Only the road, the view and the people you love.",pillars:["Curated routes, not maps","A personal concierge, not a call centre","Memories, not itineraries"],ways:"Five ways to travel",level:"One standard. Your level of freedom.",collectionCopy:"Every MLT collection is a complete journey, shaped around the way you want to move.",experience:"Experiences",reason:"Every journey begins with a reason.",reasonCopy:"People do not buy a motorhome. They choose the story they will still be telling ten years from now.",experiences:["Family expedition","Romantic escape","Wine journey","CEO escape"],map:"MLT Smart Map",mapTitle:"Remarkable places. One intelligent route.",mapCopy:"Explore curated campsites, vineyards, lakes, mountain passes and quiet coastlines. Choose what calls to you; MLT will compose the journey between them.",view:"View map",selected:"Selected places",distance:"You will travel",open:"Choose a collection"},
  de:{hero:"Wir schaffen Momente, die für immer bleiben — in Europas außergewöhnlichsten Landschaften und bis ins Detail durchdacht.",choose:"Kollektion wählen",philosophy:"Die MLT Philosophie",freedom:"Freiheit, um die sich bereits jemand gekümmert hat.",freedomCopy:"Wir schaffen die Freiheit, den Moment einfach zu leben. Keine Planung. Kein Stress. Nur die Straße, die Aussicht und die Menschen, die Sie lieben.",pillars:["Kuratierte Routen statt Karten","Persönlicher Concierge statt Callcenter","Erinnerungen statt Reisepläne"],ways:"Fünf Arten zu reisen",level:"Ein Standard. Ihre Freiheit.",collectionCopy:"Jede MLT Kollektion ist eine vollständige Reise — abgestimmt auf Ihre Art zu reisen.",experience:"Erlebnisse",reason:"Jede Reise beginnt mit einem Grund.",reasonCopy:"Menschen wählen die Geschichte, die sie noch in zehn Jahren erzählen werden.",experiences:["Familienexpedition","Romantische Reise","Weinreise","CEO-Auszeit"],map:"MLT Smart Map",mapTitle:"Besondere Orte. Eine intelligente Route.",mapCopy:"Wählen Sie besondere Orte; MLT komponiert die Reise dazwischen.",view:"Karte ansehen",selected:"Ausgewählte Orte",distance:"Sie fahren",open:"Kollektion wählen"},
  ru:{hero:"Мы создаём моменты, которые остаются с вами навсегда — среди самых удивительных пейзажей Европы, с вниманием к каждой детали.",choose:"Выбрать коллекцию",philosophy:"Философия MLT",freedom:"Свобода, о которой уже позаботились.",freedomCopy:"Мы создаём свободу просто жить моментом. Без планирования. Без стресса. Только дорога, вид и люди, которых вы любите.",pillars:["Курированные маршруты, а не карты","Персональный консьерж, а не колл-центр","Воспоминания, а не планы поездки"],ways:"Пять способов путешествовать",level:"Один стандарт. Ваш уровень свободы.",collectionCopy:"Каждая коллекция MLT — целостное путешествие, созданное вокруг вашего ритма.",experience:"Впечатления",reason:"Каждое путешествие начинается с причины.",reasonCopy:"Люди выбирают историю, которую будут рассказывать и через десять лет.",experiences:["Семейная экспедиция","Романтическое путешествие","Винное путешествие","Перезагрузка руководителя"],map:"Умная карта MLT",mapTitle:"Особенные места. Один умный маршрут.",mapCopy:"Выбирайте интересные места; MLT составит путешествие между ними.",view:"Смотреть карту",selected:"Выбранные места",distance:"Вы проедете",open:"Выбрать коллекцию"}
} as const;
export default function MobileHomePreview({initialLocale="en",previewMode=true}:{initialLocale?:Locale;previewMode?:boolean}){
 const locale=initialLocale,[selected,setSelected]=useState(["dolomites","como"]),[distance,setDistance]=useState<number|null>(null); const t=text[locale];
 const pageRef=useRef<HTMLElement>(null);
 const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);
 const onDistance=useCallback((value:number|null)=>setDistance(value),[]);
 useEffect(()=>{const root=pageRef.current;if(!root||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const items=Array.from(root.querySelectorAll<HTMLElement>("[data-mobile-reveal]")),initialItems=items.filter(item=>item.getBoundingClientRect().top<window.innerHeight*.94);root.classList.add(styles.revealReady);const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.classList.add(styles.visible);observer.unobserve(entry.target)}),{rootMargin:"0px 0px -7% 0px",threshold:.1});items.forEach(item=>{if(!initialItems.includes(item))observer.observe(item)});let revealFrame=0;const prepareFrame=requestAnimationFrame(()=>{revealFrame=requestAnimationFrame(()=>initialItems.forEach(item=>item.classList.add(styles.visible)))});return()=>{cancelAnimationFrame(prepareFrame);cancelAnimationFrame(revealFrame);observer.disconnect();root.classList.remove(styles.revealReady)}},[]);
 return <main ref={pageRef} className={styles.stage}><div className={styles.phone}>
  <MobilePreviewHeader locale={locale} previewMode={previewMode}/><section className={styles.hero}><img src="/hero-mediterranean-sunset.jpg" alt=""/><div className={`${styles.heroCopy} ${styles.heroEnter}`}><p>INDIVIDUAL ROAD<br/>EXPEDITIONS</p><span>{t.hero}</span><a href="#collections" onClick={scrollCollectionCarouselIntoView}>{t.choose}</a></div></section>
  <section className={styles.section}><label data-mobile-reveal="up">01 / {t.philosophy}</label><h1 data-mobile-reveal="up">{t.freedom}</h1><p className={styles.lead} data-mobile-reveal="up">{t.freedomCopy}</p><div className={styles.pillars}>{t.pillars.map((x,i)=><article key={x} data-mobile-reveal="up"><img src={philosophyImages[i]} alt="" loading="lazy" decoding="async"/><h3>{x}</h3></article>)}</div></section>
  <section className={styles.section} id="collections"><label>02 / {t.ways}</label><h2>{t.level}</h2><p className={styles.lead}>{t.collectionCopy}</p><CollectionCarousel items={collections} shellClassName={styles.railWrap} carouselClassName={styles.slider} slideClassName={styles.slide} arrowClassName={styles.sliderArrow} previousIcon="‹" nextIcon="›" renderSlide={(c,i)=><a href={previewMode?`/${locale}/collections/${c[0]}/mobile-preview/`:`/${locale}/collections/${c[0]}/`}><img src={c[2]} alt="" draggable="false"/><div><small>0{(i%collections.length)+1}</small><h3>MLT {c[1]}<em>Collection</em></h3><p>{c[3]} · {c[4]}</p><b>EXPLORE COLLECTION →</b></div></a>}/></section>
  <section className={styles.section} id="experiences"><label data-mobile-reveal="up">03 / {t.experience}</label><h2 data-mobile-reveal="up">{t.reason}</h2><p className={styles.lead} data-mobile-reveal="up">{t.reasonCopy}</p><div className={styles.experiences}>{t.experiences.map((x,i)=><article key={x} data-mobile-reveal="up"><img src={experienceImages[i]} alt="" loading="lazy" decoding="async"/><div><h3>{x}</h3><p>{i===0?t.pillars[0]:i===1?t.pillars[2]:t.collectionCopy}</p></div></article>)}</div></section>
  <section className={`${styles.section} ${styles.mapSection}`} id="map"><label data-mobile-reveal="up">04 / {t.map}</label><h2 data-mobile-reveal="up">{t.mapTitle}</h2><p className={styles.lead} data-mobile-reveal="up">{t.mapCopy}</p><div className={styles.mapBox} data-mobile-reveal="scale"><a href={`/${locale}/plan`}>{t.view} →</a><RealRouteMap selected={selected} country="All" onToggle={toggle} locale={locale} className={styles.map} onDistanceChange={onDistance}/></div><div className={styles.selection} data-mobile-reveal="up"><header><b>{t.selected}</b><span>{selected.length} / {mapPoints.length}</span></header>{selected.map((id,i)=>{const p=mapPoints.find(x=>x.id===id);return p&&<div className={styles.selectedPlace} key={id}><i>{i+1}</i><span>{p.name}</span><button type="button" onClick={()=>toggle(id)} aria-label={`Remove ${p.name}`}>×</button></div>})}{distance!==null&&<strong>{t.distance} {distance.toLocaleString(locale)} km</strong>}</div><a className={styles.finalButton} data-mobile-reveal="up" href="#collections" onClick={scrollCollectionCarouselIntoView}>{t.open}</a></section>
  <MobilePreviewFooter locale={locale} previewMode={previewMode}/>
 </div></main>
}
