"use client";
import { useState } from "react";
import type { Locale } from "../../content/i18n";
import styles from "./mobile-preview-header.module.css";
const labels={en:{menu:"Explore MLT",collections:"Collections",journeys:"Journeys",vehicles:"Vehicles",experiences:"Experiences",map:"Smart map",account:"Sign in",contact:"Contact",chat:"Chat will be available later"},de:{menu:"MLT entdecken",collections:"Kollektionen",journeys:"Reisen",vehicles:"Fahrzeuge",experiences:"Erlebnisse",map:"Smart Map",account:"Anmelden",contact:"Kontakt",chat:"Chat ist bald verfügbar"},ru:{menu:"Откройте MLT",collections:"Коллекции",journeys:"Маршруты",vehicles:"Автодома",experiences:"Впечатления",map:"Карта",account:"Войти",contact:"Контакты",chat:"Чат скоро появится"},it:{menu:"Scopri MLT",collections:"Collezioni",journeys:"Viaggi",vehicles:"Veicoli",experiences:"Esperienze",map:"Mappa",account:"Accedi",contact:"Contatti",chat:"La chat sarà presto disponibile"},pl:{menu:"Poznaj MLT",collections:"Kolekcje",journeys:"Podróże",vehicles:"Pojazdy",experiences:"Doświadczenia",map:"Mapa",account:"Zaloguj się",contact:"Kontakt",chat:"Czat będzie wkrótce dostępny"}} as const;
function Icon({name}:{name:"globe"|"user"|"menu"|"chevron"|"chat"}){return <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">{name==="globe"&&<><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3.2 3 14.8 0 18M12 3c-3 3.2-3 14.8 0 18"/></>}{name==="user"&&<><circle cx="12" cy="8" r="3.5"/><path d="M5 21c.7-4.2 3.1-6.3 7-6.3s6.3 2.1 7 6.3"/></>}{name==="menu"&&<path d="M5 8h14M5 16h14"/>}{name==="chevron"&&<path d="m7 9.5 5 5 5-5"/>}{name==="chat"&&<><path d="M20 15a4 4 0 0 1-4 4H8l-4 2 1.2-4A8 8 0 1 1 20 15Z"/><path d="M9 12h.01M12 12h.01M15 12h.01"/></>}</svg>}
export default function MobilePreviewHeader({locale,variant="overlay",previewMode=true}:{locale:Locale;variant?:"light"|"overlay";previewMode?:boolean}){
 const [languageOpen,setLanguageOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),t=labels[locale],home=previewMode?`/${locale}/mobile-preview/`:`/${locale}/`;
 const chooseLocale=(code:Locale)=>{if(code===locale){setLanguageOpen(false);return}const url=new URL(window.location.href),parts=url.pathname.split("/");if(["en","de","ru","it","pl"].includes(parts[1]))parts[1]=code;else parts.splice(1,0,code);url.pathname=parts.join("/");window.location.assign(url.toString())};
 return <div className={`${styles.shell} ${variant==="overlay"?styles.overlay:styles.light}`}><header className={styles.header}><a className={styles.logo} href={home} aria-label="MLT mobile preview home"><img src="/mlt-logo.svg?v=20261006-vector" alt="MLT"/></a><div className={styles.actions}><div className={styles.languageWrap}><button className={styles.language} aria-expanded={languageOpen} onClick={()=>{setLanguageOpen(!languageOpen);setMenuOpen(false)}}><Icon name="globe"/><span>{locale.toUpperCase()}</span><Icon name="chevron"/></button>{languageOpen&&<div className={styles.languageMenu}>{(["en","de","ru","it","pl"] as Locale[]).map(code=><button key={code} className={locale===code?styles.activeLanguage:""} onClick={()=>chooseLocale(code)}>{code.toUpperCase()}<span>{locale===code?"✓":""}</span></button>)}</div>}</div><a className={styles.iconButton} href={`/${locale}/account`} aria-label={t.account}><Icon name="user"/></a><button className={styles.iconButton} onClick={()=>{setMenuOpen(!menuOpen);setLanguageOpen(false)}} aria-expanded={menuOpen} aria-label="Toggle menu"><Icon name="menu"/></button></div></header>{menuOpen&&<div className={styles.mobileMenu}><div className={styles.mobileMenuHead}><img src="/mlt-logo.svg?v=20261006-vector" alt="MLT"/><button onClick={()=>setMenuOpen(false)}>×</button></div><p>{t.menu}</p><nav><a href={`${home}#collections`}><span>01</span>{t.collections}</a><a href={`/${locale}/#routes`}><span>02</span>{t.journeys}</a><a href={`/${locale}/#fleet`}><span>03</span>{t.vehicles}</a><a href={`${home}#experiences`}><span>04</span>{t.experiences}</a><a href={`${home}#map`}><span>05</span>{t.map}</a></nav><div className={styles.mobileMenuBottom}><a href={`/${locale}/account`}>{t.account}</a><a href="mailto:info@mlt-lifestyle.com">{t.contact} →</a></div></div>}<button className={styles.chatButton} type="button" aria-label={t.chat} title={t.chat}><Icon name="chat"/></button></div>;
}
