"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Swiper as SwiperCarousel, SwiperSlide } from "swiper/react";
import type { Swiper as SwiperInstance } from "swiper";
import { EffectCoverflow, Keyboard } from "swiper/modules";
import "swiper/css";
import "swiper/css/effect-coverflow";
import { journeyRoutes, type Collection } from "../../../content/mlt";
import { collectionDe, collectionRu, type Locale } from "../../../content/i18n";
import { collectionDetails } from "../../../content/collection-details";
import { parseDepartureRule, useCatalogItems } from "../../../content/catalog-client";
import { LanguageMenu } from "../../LanguageMenu";
import { DepartureCalendar, type DepartureRule } from "./DepartureCalendar";
import { continueJourneyInAccount } from "../../../content/account-draft";

type CatalogItem = {
  id: number; item_type: "collection" | "product" | "route" | "extra"; collection_id: string | null;
  slug: string; title: string; subtitle: string | null; image_path: string | null; price: string | number | null;
  data_json: string | null; sort_order: number; is_active: number | boolean;
};

type ProductCard = { id: string; number: string; name: string; image: string; description: string };
type PackageVariant = { id: string; title: string; subtitle?: string; description?: string; benefits?: string[]; interests?: string[]; supplement?: string };

const rates = { freedom: [{ d: 7, p: 1490 }, { d: 10, p: 1990 }, { d: 14, p: 2590 }, { d: 21, p: 3690 }, { d: 30, p: 4990 }], signature: [{ d: 7, p: 2490 }, { d: 10, p: 3290 }, { d: 14, p: 4390 }], concierge: [{ d: 7, p: 4990 }, { d: 10, p: 6590 }, { d: 14, p: 8990 }], private: [{ d: 7, p: 19900 }, { d: 10, p: 27900 }, { d: 14, p: 38900 }, { d: 21, p: 59900 }], honeymoon: [{ d: 7, p: 5900 }, { d: 10, p: 7000 }, { d: 14, p: 8900 }], proposal: [{ d: 3, p: 0 }] } as const;
const freedomPlusRates: Record<number, number> = { 7: 1790, 10: 2340, 14: 3040, 21: 4190, 30: 5490 };
const signatureTailoredRates: Record<number, number> = { 7: 2990, 10: 4290, 14: 5890 };
const tailoredInterestOptions = [
  { id: "mountains", en: "Mountains", de: "Berge", ru: "Горы" }, { id: "restaurants", en: "Restaurants", de: "Restaurants", ru: "Рестораны" },
  { id: "wineries", en: "Wineries", de: "Weingüter", ru: "Винодельни" }, { id: "lakes", en: "Lakes", de: "Seen", ru: "Озёра" },
  { id: "spa", en: "Spa", de: "Spa", ru: "Спа" }, { id: "hiking", en: "Hiking", de: "Wandern", ru: "Пешие прогулки" },
  { id: "castles", en: "Castles", de: "Schlösser", ru: "Замки" }, { id: "cycling", en: "Cycling", de: "Fahrräder", ru: "Велосипеды" },
  { id: "yachts", en: "Yachts", de: "Yachten", ru: "Яхты" }, { id: "photo-session", en: "Photo session", de: "Fotoshooting", ru: "Фотосессия" },
  { id: "sunrise", en: "Sunrise", de: "Sonnenaufgang", ru: "Рассвет" }, { id: "birthday", en: "Birthday", de: "Geburtstag", ru: "День рождения" },
  { id: "proposal", en: "Proposal", de: "Heiratsantrag", ru: "Предложение" }, { id: "anniversary", en: "Anniversary", de: "Jahrestag", ru: "Годовщина" },
];
const hero: Record<string, string> = { freedom: "collection-freedom-hero", signature: "collection-signature-hero", concierge: "collection-concierge-hero", private: "collection-private-hero", honeymoon: "collection-honeymoon" };
const dateIso = (value: Date) => value.toISOString().slice(0, 10);
const routeCarouselCopies = 9;
const routeCarouselItems = Array.from({ length: routeCarouselCopies }, () => journeyRoutes).flat();
const routeCarouselStart = journeyRoutes.length * Math.floor(routeCarouselCopies / 2) + 3;
const signatureRoutes = [
  { id: "signature-dolomites", number: "01", name: "Dolomites Signature Route", image: "/signature-route-dolomites.jpg", tagline: { en: "Boutique hotels and panoramic views", de: "Boutique-Hotels und Panoramablicke" } },
  { id: "signature-bavaria", number: "02", name: "Bavaria Signature Experience", image: "/signature-route-bavaria.jpg", tagline: { en: "Royal Sites and Tastings", de: "Königliche Sehenswürdigkeiten und Verkostungen" } },
  { id: "signature-alpine", number: "03", name: "Alpine Escape Signature", image: "/signature-route-alpine.jpg", tagline: { en: "Cozy Chalet and Spa Retreat", de: "Gemütliches Chalet und Spa-Auszeit" } },
  { id: "signature-wine", number: "04", name: "Wine Roads Signature Cellars", image: "/signature-route-wine.jpg", tagline: { en: "Top Wineries and Sommeliers", de: "Spitzenweingüter und Sommeliers" } },
  { id: "signature-mediterranean", number: "05", name: "Mediterranean Signature Riviera", image: "/signature-route-mediterranean.jpg", tagline: { en: "Yachts and signature restaurants", de: "Yachten und Signature-Restaurants" } },
  { id: "signature-winter", number: "06", name: "Winter Alps Signature", image: "/signature-route-winter.jpg", tagline: { en: "Ski pass and mountain chalet", de: "Skipass und Bergchalet" } },
  { id: "signature-black-forest", number: "07", name: "Black Forest Signature Retreat", image: "/signature-route-black-forest.jpg", tagline: { en: "Historic Sites and Thermal Baths", de: "Historische Stätten und Thermalbäder" } },
];
const signatureCarouselItems = Array.from({ length: routeCarouselCopies }, () => signatureRoutes).flat();
const conciergeFamilyRoutes = [
  { id: "family-dolomites", number: "01", name: "Family Dolomites Expedition", image: "/concierge-family-dolomites.jpg", tagline: "Effortless alpine peaks where we handle every detail" },
  { id: "family-bavaria", number: "02", name: "Bavaria Family Tales & Lakes", image: "/concierge-family-bavaria.jpg", tagline: "Seamless fairy-tale lakes fully orchestrated by us" },
  { id: "family-alpine", number: "03", name: "Alpine Family Sanctuary", image: "/concierge-family-alpine.jpg", tagline: "A secure family haven where we anticipate everything" },
  { id: "family-wine", number: "04", name: "Wine Roads Family Estates", image: "/concierge-family-wine.jpg", tagline: "Expertly curated vineyard discovery fully managed by us" },
  { id: "family-mediterranean", number: "05", name: "Mediterranean Family Riviera", image: "/concierge-family-mediterranean.jpg", tagline: "Sun-kissed coastal retreat with every detail handled by us" },
  { id: "family-winter", number: "06", name: "Winter Alps Family Wonderland", image: "/concierge-family-winter.jpg", tagline: "A magical snowbound escape completely arranged by us" },
  { id: "family-black-forest", number: "07", name: "Black Forest Family Forest & Lore", image: "/concierge-family-black-forest.jpg", tagline: "Enchanted woodland exploration entirely looked after by us" },
];
const conciergeCarouselItems = Array.from({ length: routeCarouselCopies }, () => conciergeFamilyRoutes).flat();
const honeymoonRoutes = [
  { id: "honeymoon-dolomites", number: "01", name: "Dolomites Peak Romance", image: "/honeymoon-dolomites.jpg", copy: { en: "Flowing Alpine roads, a panoramic plateau and sunset peaks shared in complete privacy.", de: "Sanfte Alpenstraßen, ein Panoramaplateau und Gipfel im Abendlicht — ganz für Sie allein.", ru: "Плавные серпантины альпийских дорог, парковка на панорамном плато, вечерний чай с видом на закатные вершины и полное ощущение уединения наедине друг с другом." } },
  { id: "honeymoon-bavaria", number: "02", name: "Bavarian Lake Serenade", image: "/honeymoon-bavaria.jpg", copy: { en: "Quiet lakeside stays, sunset walks to old castles and slow breakfasts by the water.", de: "Ruhige Stellplätze am See, Spaziergänge zu alten Schlössern und langsame Frühstücke am Wasser.", ru: "Уютные стоянки у зеркальной глади баварских озер, романтические прогулки на закате к старинным замкам и неспешные завтраки на террасе автодома." } },
  { id: "honeymoon-alpine", number: "03", name: "The Alpine Hideaway Route", image: "/honeymoon-alpine.jpg", copy: { en: "Hidden mountain valleys, pine-scented air and the feeling that the world belongs only to you.", de: "Verborgene Bergtäler, der Duft von Kiefern und das Gefühl, die Welt gehöre nur Ihnen.", ru: "Побег от городской суеты в скрытые от посторонних глаз горные долины, хвойный воздух, ковер из полевых цветов и абсолютная безопасность в пути." } },
  { id: "honeymoon-vineyards", number: "04", name: "Vineyards & Vows Journey", image: "/honeymoon-vineyards.jpg", copy: { en: "European wine roads, private tastings and intimate evenings beneath a sky full of stars.", de: "Europäische Weinstraßen, private Verkostungen und intime Abende unter dem Sternenhimmel.", ru: "Путешествие по живописным винодельческим дорогам Европы, парковка среди ухоженных лоз, дегустации местных вин и камерные вечера под звездным небом." } },
  { id: "honeymoon-riviera", number: "05", name: "Riviera Sunset Route", image: "/honeymoon-riviera.jpg", copy: { en: "Azure coves, sea-view terraces and the warm romantic rhythm of the Mediterranean.", de: "Türkisfarbene Buchten, Terrassen am Meer und der warme romantische Rhythmus des Mittelmeers.", ru: "Мягкий климат лазурного побережья, безопасные прибрежные террасы с видом на бирюзовые бухты, шум прибоя и средиземноморский романтический вайб." } },
  { id: "honeymoon-snow", number: "06", name: "Snowflake Alpine Dream", image: "/honeymoon-snow.jpg", copy: { en: "Snow-covered firs, warm lights, mulled wine and a cosy retreat after a winter walk.", de: "Verschneite Tannen, warmes Licht, Glühwein und ein gemütlicher Rückzugsort nach dem Winterspaziergang.", ru: "Зимняя сказка для двоих, заснеженные ели за панорамным окном автодома, теплый свет гирлянд, горячий глинтвейн и уют после прогулки." } },
  { id: "honeymoon-black-forest", number: "07", name: "Black Forest Fairy Tale", image: "/honeymoon-black-forest.jpg", copy: { en: "Secret forest roads, storybook landscapes and long evenings beneath whispering leaves.", de: "Geheime Waldstraßen, märchenhafte Landschaften und lange Abende unter rauschenden Blättern.", ru: "Таинственная и уютная атмосфера старинного леса, уединенные лесные дороги, сказочные пейзажи и вечерние разговоры у кемпера под шепот листвы." } },
];
const privateRoutes = [
  { id: "private-dolomites", number: "01", name: "Dolomites Grand Tour", image: "/private-route-dolomites.webp", tagline: { en: "Majestic alpine panoramas paired with flawless elite service", de: "Majestätische Alpenpanoramen mit makellosem Elite-Service", ru: "Величественные альпийские панорамы и безупречный элитный сервис" } },
  { id: "private-bavaria", number: "02", name: "Lakes of Bavaria", image: "/private-route-bavaria.webp", tagline: { en: "Royal tranquility along crystal-clear waters in absolute privacy", de: "Königliche Ruhe an kristallklaren Gewässern in absoluter Privatsphäre", ru: "Королевское спокойствие у кристально чистых озёр в полной приватности" } },
  { id: "private-alpine", number: "03", name: "Alpine Escape", image: "/private-route-alpine.webp", tagline: { en: "The ultimate high-altitude sanctuary of uncompromising comfort", de: "Ein alpiner Rückzugsort mit kompromisslosem Komfort", ru: "Высокогорное уединение с бескомпромиссным комфортом" } },
  { id: "private-wine", number: "04", name: "Wine Roads Collection", image: "/private-route-wine.webp", tagline: { en: "Private tastings across legendary vineyards reserved for the elite", de: "Private Verkostungen in legendären Weingütern, exklusiv für die Elite", ru: "Частные дегустации на легендарных виноградниках для избранных" } },
  { id: "private-mediterranean", number: "05", name: "Mediterranean Discovery", image: "/private-route-mediterranean.webp", tagline: { en: "Sun-drenched secluded coasts experienced in unmatched style", de: "Sonnenverwöhnte, verborgene Küsten in unvergleichlichem Stil", ru: "Солнечные уединённые побережья в непревзойдённом стиле" } },
  { id: "private-winter", number: "06", name: "Winter Alps Expedition", image: "/private-route-winter.webp", tagline: { en: "Pristine snowbound peaks paired with bespoke alpine luxury", de: "Unberührte verschneite Gipfel mit maßgeschneidertem Alpenluxus", ru: "Нетронутые снежные вершины и персональная альпийская роскошь" } },
  { id: "private-black-forest", number: "07", name: "Black Forest Experience", image: "/private-route-black-forest.webp", tagline: { en: "Enchanted ancient woodlands offering total seclusion and refinement", de: "Verwunschene alte Wälder mit vollkommener Abgeschiedenheit und Raffinesse", ru: "Древние волшебные леса, полное уединение и утончённость" } },
];
const privateCarouselItems = Array.from({ length: routeCarouselCopies }, () => privateRoutes).flat();
export function CollectionDetail({ collection }: { collection: Collection }) {
  const routeCarousel = useRef<SwiperInstance | null>(null);
  const fallbackOptions = rates[collection.id as keyof typeof rates];
  const [locale, setLocale] = useState<Locale>("en");
  const catalogItems = useCatalogItems() as CatalogItem[];
  const [days, setDays] = useState(fallbackOptions[0].d); const [start, setStart] = useState(""); const [guests, setGuests] = useState(1); const [plus, setPlus] = useState(false); const [customPackage, setCustomPackage] = useState(0); const [menuOpen, setMenuOpen] = useState(false); const [selectedRoute, setSelectedRoute] = useState(""); const [tailoredInterests, setTailoredInterests] = useState<string[]>([]); const [error, setError] = useState(""); const [country, setCountry] = useState("Italy");
  useEffect(() => { const pathLocale = location.pathname.split("/")[1]; const savedLocale = localStorage.getItem("mlt-locale"); if (["en", "de", "ru"].includes(pathLocale)) setLocale(pathLocale as Locale); else if (["en", "de", "ru"].includes(savedLocale || "")) setLocale(savedLocale as Locale); }, [collection.id]);
  const dbCollection = catalogItems.find((entry) => entry.item_type === "collection" && entry.slug === collection.id && Boolean(entry.is_active));
  const options = useMemo(() => { if (!dbCollection?.data_json) return fallbackOptions; try { const parsed = JSON.parse(dbCollection.data_json) as { pricing?: Array<{ days?: unknown; price?: unknown }> }; const rows = (parsed.pricing || []).map((row) => ({ d: Number(row.days), p: Number(row.price) })).filter((row) => Number.isFinite(row.d) && row.d > 0 && Number.isFinite(row.p) && row.p >= 0).sort((a, b) => a.d - b.d); return rows.length ? rows : fallbackOptions; } catch { return fallbackOptions; } }, [dbCollection, fallbackOptions]);
  const customPackages = useMemo<PackageVariant[]>(() => { if (!dbCollection?.data_json) return []; try { const rows = (JSON.parse(dbCollection.data_json) as { packageVariants?: unknown }).packageVariants; if (!Array.isArray(rows)) return []; return rows.filter((row): row is PackageVariant => Boolean(row && typeof row === "object" && "title" in row && String((row as PackageVariant).title).trim())); } catch { return []; } }, [dbCollection]);
  const departureRule = useMemo<DepartureRule>(() => parseDepartureRule(dbCollection?.data_json), [dbCollection]);
  useEffect(() => { if (!options.some((option) => option.d === days)) setDays(options[0].d); }, [days, options]);
  const localizedItem = locale === "de" ? { ...collection, ...collectionDe[collection.id] } : locale === "ru" ? { ...collection, ...collectionRu[collection.id] } : collection;
  const item = dbCollection ? { ...localizedItem, name: dbCollection.title.replace(/^MLT\s+/i, "").replace(/\s+Collection$/i, ""), eyebrow: dbCollection.subtitle || localizedItem.eyebrow } : localizedItem;
  const copy = collectionDetails[collection.id][locale]; const selected = options.find((option) => option.d === days) || options[0];
  const end = useMemo(() => { if (!start) return ""; const next = new Date(`${start}T12:00:00`); next.setDate(next.getDate() + days); return dateIso(next); }, [start, days]);
  const tailored = collection.id === "signature" && plus; const selectedPrice = collection.id === "freedom" && plus ? freedomPlusRates[days] : tailored ? signatureTailoredRates[days] : selected.p; const total = selectedPrice + Math.max(0, guests - 2) * 190; const de = locale === "de"; const ru = locale === "ru"; const tr = (en: string, deText: string, ruText: string) => de ? deText : ru ? ruText : en;
  const t = ru ? { choose: "Выберите даты", country: "Страна", departure: "Отправление", return: "Возвращение", guests: "Путешественники", total: "Итого", pay: "Войти и оплатить", error: "Сначала выберите дату отправления.", contact: "Связаться с консьержем" } : de ? { choose: "Reisedaten wählen", country: "Land", departure: "Abreise", return: "Rückgabe", guests: "Reisende", total: "Gesamt", pay: "Anmelden & bezahlen", error: "Bitte wählen Sie zuerst ein Abreisedatum.", contact: "Concierge kontaktieren" } : { choose: "Choose your travel dates", country: "Country", departure: "Departure", return: "Return", guests: "Travellers", total: "Total", pay: "Sign in & pay", error: "Please choose a departure date first.", contact: "Talk to a concierge" };
  const money = (value: number) => new Intl.NumberFormat(de ? "de-DE" : ru ? "ru-RU" : "en-GB", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value);
  const displayDate = (value: string) => value ? new Intl.DateTimeFormat(de ? "de-DE" : ru ? "ru-RU" : "en-GB", { day: "numeric", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00`)) : "—";
  const fallbackProducts = useMemo<ProductCard[]>(() => { const source = collection.id === "signature" ? signatureRoutes : collection.id === "concierge" ? conciergeFamilyRoutes : collection.id === "private" ? privateRoutes : collection.id === "honeymoon" ? honeymoonRoutes : journeyRoutes; return source.map((route, index) => { const translated = "copy" in route ? (ru ? route.copy.ru : de ? route.copy.de : route.copy.en) : "tagline" in route ? (typeof route.tagline === "string" ? route.tagline : ru && "ru" in route.tagline ? route.tagline.ru : de ? route.tagline.de : route.tagline.en) : ""; return { id: route.id, number: route.number || String(index + 1).padStart(2, "0"), name: route.name, image: route.image, description: translated }; }); }, [collection.id, de, ru]);
  const products = useMemo<ProductCard[]>(() => { const rows = catalogItems.filter((entry) => entry.item_type === "product" && entry.collection_id === collection.id && Boolean(entry.is_active)).sort((a, b) => Number(a.sort_order) - Number(b.sort_order)); if (!rows.length) return fallbackProducts; return rows.map((entry, index) => { const translatedFallback = fallbackProducts.find((product) => product.id === entry.slug); return { id: entry.slug, number: String(index + 1).padStart(2, "0"), name: entry.title, image: entry.image_path || translatedFallback?.image || "/collection-freedom.webp", description: translatedFallback?.description || entry.subtitle || "" }; }); }, [catalogItems, collection.id, fallbackProducts]);
  const productSlides = useMemo(() => Array.from({ length: 3 }, () => products).flat(), [products]);
  const services = useMemo(() => { const rows = catalogItems.filter((entry) => entry.item_type === "extra" && entry.collection_id === collection.id && Boolean(entry.is_active)).sort((a, b) => Number(a.sort_order) - Number(b.sort_order)); return rows.length ? rows.map((entry) => entry.title) : item.inclusions; }, [catalogItems, collection.id, item.inclusions]);
  const defaultHeroPaths = ["webp", "jpg", "png", "avif"].map((extension) => `/collection-${collection.id}.${extension}`);
  const useResponsiveHero = !dbCollection?.image_path || defaultHeroPaths.includes(dbCollection.image_path);
  const desktopHeroBase = collection.id === "honeymoon" ? "collection-honeymoon-hero-v2" : hero[collection.id];
  const mobileHeroBase = `collection-${collection.id}-hero-mobile-v2`;
  const heroPreview = dbCollection?.image_path || `/collection-${collection.id}.webp`;
  const pay = () => { if (!start) return setError(t.error); const routeName = products.find((route) => route.id === selectedRoute)?.name || "MLT curated route"; continueJourneyInAccount({ collection: collection.id, collectionName: `MLT ${item.name} Collection`, country, days, arrival: start, departure: end, guests, route: routeName, rate: selectedPrice > 0 ? money(total) : "On request", signatureTailored: tailored, freedomPlus: collection.id === "freedom" && plus, tailoredInterests, vehicle: "MLT motorhome" }, locale); };
  const changeLanguage = (next: Locale) => { localStorage.setItem("mlt-locale", next); const parts = location.pathname.split("/"); if (["en", "de", "ru"].includes(parts[1])) parts[1] = next; else parts.splice(1, 0, next); location.assign(`${parts.join("/")}${location.search}${location.hash}`); };
  const chooseRoute = (routeId: string) => setSelectedRoute(routeId);
  const chooseSignatureRoute = (routeId: string) => setSelectedRoute(routeId);
  const choosePrivateRoute = (routeId: string) => setSelectedRoute(routeId);
  const selectSignaturePackage = (isTailored: boolean) => { setPlus(isTailored); try { const draft = JSON.parse(localStorage.getItem("mlt-journey-draft") || "{}"); localStorage.setItem("mlt-journey-draft", JSON.stringify({ ...draft, collection: "signature", signatureTailored: isTailored, tailoredInterests })); } catch {} };
  const toggleTailoredInterest = (interestId: string) => { const next = tailoredInterests.includes(interestId) ? tailoredInterests.filter((id) => id !== interestId) : [...tailoredInterests, interestId]; setTailoredInterests(next); try { const draft = JSON.parse(localStorage.getItem("mlt-journey-draft") || "{}"); localStorage.setItem("mlt-journey-draft", JSON.stringify({ ...draft, collection: "signature", signatureTailored: true, tailoredInterests: next })); } catch {} };
  const keepRouteCarouselCentered = (instance: SwiperInstance) => {
    const routeIndex = ((instance.activeIndex % journeyRoutes.length) + journeyRoutes.length) % journeyRoutes.length;
    if (instance.activeIndex < journeyRoutes.length * 2 || instance.activeIndex >= journeyRoutes.length * (routeCarouselCopies - 2)) {
      instance.slideTo(journeyRoutes.length * Math.floor(routeCarouselCopies / 2) + routeIndex, 0, false);
    }
    return routeIndex;
  };
  return <main className={`collection-page collection-unified collection-${collection.id}${customPackages.length ? " collection-db-packages" : ""}`}>
    {useResponsiveHero ? <><link rel="preload" as="image" href={`/${desktopHeroBase}.avif`} type="image/avif" media="(min-width: 701px)" fetchPriority="high" /><link rel="preload" as="image" href={`/${mobileHeroBase}.avif`} type="image/avif" media="(max-width: 700px)" fetchPriority="high" /></> : <link rel="preload" as="image" href={dbCollection?.image_path} fetchPriority="high" />}
    <header className="light-nav"><a className="light-brand" href={`/${locale}/`} aria-label="MLT home"><img src="/mlt-logo.svg" alt="MLT — Move. Live. Travel." /></a><nav className={menuOpen ? "light-links open" : "light-links"} aria-label="Primary navigation"><a href={`/${locale}/#collections`}>{tr("Collections", "Kollektionen", "Коллекции")}</a><a href={`/${locale}/#experiences`}>{tr("Experiences", "Erlebnisse", "Впечатления")}</a><a href={`/${locale}/#smart-map`}>{tr("Smart Map", "Smart Map", "Умная карта")}</a><a href={`/${locale}/#about`}>{tr("About", "Über MLT", "О MLT")}</a></nav><div className="light-actions"><LanguageMenu locale={locale} onChange={changeLanguage} /><a className="account-nav-link" href={`/${locale}/account/`} aria-label={tr("My account", "Mein Konto", "Личный кабинет")}><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3.5" /><path d="M4.5 20c.8-3.7 3.3-5.5 7.5-5.5s6.7 1.8 7.5 5.5" /></svg></a><button className="light-menu" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label={tr("Toggle menu", "Menü öffnen", "Открыть меню")}><span /><span /></button></div></header>
    <section className="collection-hero" style={{ backgroundImage: `linear-gradient(rgba(55,45,36,.18),rgba(20,22,19,.34)),url(${heroPreview})` }}><picture className="collection-hero-media">{useResponsiveHero ? <><source media="(max-width: 700px)" srcSet={`/${mobileHeroBase}.avif`} type="image/avif" /><source media="(max-width: 700px)" srcSet={`/${mobileHeroBase}.webp`} type="image/webp" /><source srcSet={`/${desktopHeroBase}.avif`} type="image/avif" /><source srcSet={`/${desktopHeroBase}.webp`} type="image/webp" /><img src={`/${desktopHeroBase}.webp`} alt="" fetchPriority="high" decoding="async" /></> : <img src={dbCollection?.image_path} alt="" fetchPriority="high" decoding="async" />}</picture><div className="collection-hero-shade" /><div className="collection-hero-copy"><p className="light-eyebrow"><span />MLT / {item.number}</p><h1>MLT {item.name}<br /><em>Collection</em></h1><p>{copy.manifesto}</p></div></section>
    <section className="collection-booking-band"><div className="hero-booking" aria-label={t.choose}>
      {customPackages.length > 0 && (() => { const active = customPackages[Math.min(customPackage, customPackages.length - 1)]; return <div className="package-switch collection-data-packages"><span>{tr("Journey type", "Reiseart", "Тип путешествия")}</span><div>{customPackages.map((variant,index)=><button type="button" key={variant.id||index} className={index===customPackage?"active":""} onClick={()=>{setCustomPackage(index);setPlus(index>0)}}><b>{variant.title}</b><small>{variant.subtitle}</small><i>→</i></button>)}</div>{active.description&&<p className="package-description">{active.description}</p>}<ul className="package-benefits">{(active.benefits||[]).map(benefit=><li key={benefit}>{benefit}</li>)}{active.supplement&&<li className="package-supplement">{active.supplement}</li>}</ul>{Boolean(active.interests?.length)&&<div className="tailored-interests">{active.interests!.map((interest,index)=>{const key=`${active.id}-interest-${index}`;const selected=tailoredInterests.includes(key);return <button type="button" key={key} className={selected?"selected":""} aria-pressed={selected} onClick={()=>setTailoredInterests(current=>selected?current.filter(item=>item!==key):[...current,key])}>{selected&&<b>✓</b>}{interest}</button>})}</div>}</div> })()}
      {customPackages.length === 0 && collection.id === "freedom" && <div className="package-switch"><span>{tr("Journey type", "Reiseart", "Тип путешествия")}</span><div><button className={!plus ? "active" : ""} onClick={() => setPlus(false)}><b>Freedom</b><small>{tr("Independent journey", "Unabhängige Reise", "Самостоятельное путешествие")}</small><i>→</i></button><button className={plus ? "active" : ""} onClick={() => setPlus(true)}><b>Freedom+</b><small>{tr("Route & recommendations", "Route & Empfehlungen", "Маршрут и рекомендации")}</small><i>→</i></button></div><ul className="package-benefits">{plus ? <><li>{tr("Everything in Freedom", "Alles aus Freedom", "Всё из Freedom")}</li><li>{tr("Author route", "Autorenroute", "Авторский маршрут")}</li><li>{tr("Digital guide", "Digitaler Reiseführer", "Цифровой гид")}</li><li>{tr("Panoramic roads", "Panoramastraßen", "Панорамные дороги")}</li><li>{tr("Restaurant recommendations", "Restaurantempfehlungen", "Рекомендации ресторанов")}</li><li>{tr("Location recommendations", "Ortsempfehlungen", "Рекомендации мест")}</li><li className="package-supplement">* Supplement €300–500</li></> : <><li>{tr("Motorhome", "Reisemobil", "Автодом")}</li><li>{tr("Basic Road Book", "Basis-Roadbook", "Базовый путеводитель")}</li><li>{tr("MLT app", "MLT App", "Приложение MLT")}</li><li>{tr("Technical support", "Technischer Support", "Техническая поддержка")}</li></>}</ul></div>}
      {collection.id === "signature" && <div className="package-switch signature-package-switch"><span>{tr("Journey type", "Reiseart", "Тип путешествия")}</span><div><button className={!plus ? "active" : ""} onClick={() => selectSignaturePackage(false)}><b>Signature</b><small>{tr("Fully organised", "Vollständig organisiert", "Всё организовано")}</small><i>→</i></button><button className={plus ? "active" : ""} onClick={() => selectSignaturePackage(true)}><b>Signature Tailored</b><small>{tr("Designed around you", "Nur für Sie entworfen", "Создано для вас")}</small><i>→</i></button></div>{plus ? <div className="tailored-package-copy"><p>{tr("Tell us how you want to remember this journey. We shape your answers into a personal travel scenario created for your family.", "Erzählen Sie uns, wie Sie diese Reise in Erinnerung behalten möchten. Wir gestalten daraus ein persönliches Reiseszenario für Ihre Familie.", "Расскажите, каким вы хотите запомнить это путешествие. Мы создадим личный сценарий для вашей семьи.")}</p><ul className="package-benefits"><li>{tr("Everything in Signature", "Alles aus Signature", "Всё из Signature")}</li><li>{tr("Personal travel scenario", "Persönliches Reiseszenario", "Личный сценарий")}</li><li>{tr("AI-tailored route", "KI-gestützte Routenplanung", "Маршрут, созданный ИИ")}</li><li>{tr("Activities matched to your interests", "Aktivitäten nach Ihren Interessen", "Активности по вашим интересам")}</li><li>{tr("Special moments and occasions", "Besondere Momente und Anlässe", "Особые моменты и события")}</li><li className="package-supplement">* Supplement €500–1,500</li></ul><div className="tailored-interests" aria-label={tr("Choose interests", "Interessen auswählen", "Выбрать интересы")}>{tailoredInterestOptions.map((interest) => <button type="button" key={interest.id} className={tailoredInterests.includes(interest.id) ? "selected" : ""} aria-pressed={tailoredInterests.includes(interest.id)} onClick={() => toggleTailoredInterest(interest.id)}>{tailoredInterests.includes(interest.id) && <b>✓</b>}{de ? interest.de : ru ? interest.ru : interest.en}</button>)}</div></div> : <ul className="package-benefits"><li>{tr("Everything organised in advance", "Alles im Voraus organisiert", "Всё организовано заранее")}</li><li>{tr("All campsites paid", "Alle Campingplätze bezahlt", "Все кемпинги оплачены")}</li><li>{tr("Ready-made route", "Fertige Route", "Готовый маршрут")}</li><li>{tr("All reservations", "Alle Reservierungen", "Все бронирования")}</li><li>{tr("Navigation", "Navigation", "Навигация")}</li></ul>}</div>}
      {collection.id === "private" && <div className="package-switch private-package-switch"><span>{tr("Journey type", "Reiseart", "Тип путешествия")}</span><div><button className="active" type="button"><b>Private Expedition</b><small>{tr("Your private travelling team", "Ihr privates Reiseteam", "Ваша персональная команда")}</small><i>→</i></button></div><ul className="package-benefits"><li>{tr("Individual itinerary", "Individuelle Reiseroute", "Индивидуальный маршрут")}</li><li>{tr("Private driver", "Privatfahrer", "Личный водитель")}</li><li>{tr("Technician", "Techniker", "Техник")}</li><li>{tr("Chef / waiter", "Koch / Kellner", "Шеф-повар / официант")}</li><li>{tr("Half board", "Halbpension", "Полупансион")}</li><li>{tr("Private excursions", "Private Ausflüge", "Индивидуальные экскурсии")}</li><li>{tr("VIP service", "VIP-Service", "VIP-сервис")}</li><li>{tr("Transfer", "Transfer", "Трансфер")}</li><li>{tr("24/7 concierge", "Concierge rund um die Uhr", "Консьерж 24/7")}</li></ul></div>}
      <div className="booking-main"><label className="booking-date"><span>{t.country}</span><select aria-label={t.country} value={country} onChange={(event) => setCountry(event.target.value)}><option value="Italy">{tr("Italy", "Italien", "Италия")}</option></select></label><div className="booking-duration"><span>{t.choose}</span><div>{options.map((option) => <button key={option.d} className={days === option.d ? "active" : ""} onClick={() => setDays(option.d)}><b>{option.d} {tr("days", "Tage", "дней")}</b><small>{option.p ? money(collection.id === "freedom" && plus ? freedomPlusRates[option.d] : tailored ? signatureTailoredRates[option.d] : option.p) : tr("On request", "Auf Anfrage", "По запросу")}</small></button>)}</div></div><DepartureCalendar value={start} onChange={setStart} rule={departureRule} locale={locale} label={t.departure}/><div className="booking-end"><span>{t.return}</span><strong>{displayDate(end)}</strong></div><div className="guest-stepper"><span>{t.guests}</span><div><button disabled={guests <= 1} onClick={() => setGuests(Math.max(1, guests - 1))}>−</button><b>{guests}</b><button disabled={guests >= 8} onClick={() => setGuests(Math.min(8, guests + 1))}>+</button></div><small>{tr("1–2 guests included · +€190 from the 3rd guest", "1–2 Reisende inklusive · +190 € ab der 3. Person", "1–2 гостя включены · +190 € с третьего гостя")}</small></div></div>
      {collection.id === "freedom" && <div className="booking-route-picker"><div className="booking-route-head"><div><span>{de ? "Ihre Route" : "Your route"}</span><strong>{de ? "Wählen Sie Ihre Reise" : "Choose your journey"}</strong></div></div><div className="booking-route-carousel-shell"><button className="booking-route-arrow booking-route-arrow-prev" type="button" onClick={() => routeCarousel.current?.slidePrev()} aria-label={de ? "Vorherige Route" : "Previous route"}>←</button><SwiperCarousel className="booking-route-carousel" modules={[EffectCoverflow, Keyboard]} effect="coverflow" initialSlide={routeCarouselStart} centeredSlides centeredSlidesBounds={false} slidesPerView="auto" speed={850} grabCursor keyboard={{ enabled: true }} coverflowEffect={{ rotate: 0, stretch: 8, depth: 90, modifier: 1, slideShadows: false }} onSwiper={(instance) => { routeCarousel.current = instance; }} onTouchStart={(instance) => keepRouteCarouselCentered(instance)} onSliderFirstMove={(instance) => keepRouteCarouselCentered(instance)} onSlideChange={(instance) => { keepRouteCarouselCentered(instance); }} aria-label={de ? "Routen auswählen" : "Choose a route"}>{routeCarouselItems.map((route, index) => <SwiperSlide className="booking-route-slide" key={`${route.id}-${index}`}><button type="button" className={selectedRoute === route.id ? "selected" : ""} aria-pressed={selectedRoute === route.id} onClick={() => { chooseRoute(route.id); routeCarousel.current?.slideTo(index); }}><img src={route.image} alt="" draggable="false" /><span>{route.number}</span><div><strong>{route.name}</strong><small>({de ? route.tagline.de : route.tagline.en})</small></div><i>{selectedRoute === route.id ? (de ? "Ausgewählt" : "Selected") : (de ? "Auswählen" : "Choose")}</i></button></SwiperSlide>)}</SwiperCarousel><button className="booking-route-arrow booking-route-arrow-next" type="button" onClick={() => routeCarousel.current?.slideNext()} aria-label={de ? "Nächste Route" : "Next route"}>→</button></div></div>}
      {collection.id === "signature" && <div className="booking-route-picker"><div className="booking-route-head"><div><span>{de ? "Ihre Signature Route" : "Your Signature route"}</span><strong>{de ? "Wählen Sie Ihr Erlebnis" : "Choose your experience"}</strong></div></div><div className="booking-route-carousel-shell"><button className="booking-route-arrow booking-route-arrow-prev" type="button" onClick={() => routeCarousel.current?.slidePrev()} aria-label={de ? "Vorherige Route" : "Previous route"}>←</button><SwiperCarousel className="booking-route-carousel" modules={[EffectCoverflow, Keyboard]} effect="coverflow" initialSlide={routeCarouselStart} centeredSlides centeredSlidesBounds={false} slidesPerView="auto" speed={850} grabCursor keyboard={{ enabled: true }} coverflowEffect={{ rotate: 0, stretch: 8, depth: 90, modifier: 1, slideShadows: false }} onSwiper={(instance) => { routeCarousel.current = instance; }} onTouchStart={(instance) => keepRouteCarouselCentered(instance)} onSliderFirstMove={(instance) => keepRouteCarouselCentered(instance)} onSlideChange={(instance) => { keepRouteCarouselCentered(instance); }} aria-label={de ? "Signature Routen auswählen" : "Choose a Signature route"}>{signatureCarouselItems.map((route, index) => <SwiperSlide className="booking-route-slide" key={`${route.id}-${index}`}><button type="button" className={selectedRoute === route.id ? "selected" : ""} aria-pressed={selectedRoute === route.id} onClick={() => { chooseSignatureRoute(route.id); routeCarousel.current?.slideTo(index); }}><img src={route.image} alt="" draggable="false" /><span>{route.number}</span><div><strong>{route.name}</strong><small>({de ? route.tagline.de : route.tagline.en})</small></div><i>{selectedRoute === route.id ? (de ? "Ausgewählt" : "Selected") : (de ? "Auswählen" : "Choose")}</i></button></SwiperSlide>)}</SwiperCarousel><button className="booking-route-arrow booking-route-arrow-next" type="button" onClick={() => routeCarousel.current?.slideNext()} aria-label={de ? "Nächste Route" : "Next route"}>→</button></div></div>}
      {collection.id === "concierge" && <><div className="package-switch concierge-package-switch"><span>{tr("Journey type", "Reiseart", "Тип путешествия")}</span><div><button className="active" type="button"><b>Concierge</b><small>{tr("Family journeys, fully handled", "Familienreisen, komplett organisiert", "Семейные путешествия — всё организовано")}</small><i>→</i></button></div><ul className="package-benefits"><li>24/7 Online concierge</li><li>Live route changes</li><li>All campsites booked</li><li>Excursions & dining reservations</li><li>Technical support</li><li>Large motorhome for 2–5 people</li></ul></div><div className="booking-route-picker"><div className="booking-route-head"><div><span>{tr("Family Concierge journeys", "Family Concierge Reisen", "Семейные путешествия с консьержем")}</span><strong>{tr("Choose your family expedition", "Wählen Sie Ihre Familienexpedition", "Выберите семейную экспедицию")}</strong></div></div><div className="booking-route-carousel-shell"><button className="booking-route-arrow booking-route-arrow-prev" type="button" onClick={() => routeCarousel.current?.slidePrev()} aria-label={tr("Previous route", "Vorherige Route", "Предыдущий маршрут")}>←</button><SwiperCarousel className="booking-route-carousel" modules={[EffectCoverflow, Keyboard]} effect="coverflow" initialSlide={routeCarouselStart} centeredSlides centeredSlidesBounds={false} slidesPerView="auto" speed={850} grabCursor keyboard={{ enabled: true }} coverflowEffect={{ rotate: 0, stretch: 8, depth: 90, modifier: 1, slideShadows: false }} onSwiper={(instance) => { routeCarousel.current = instance; }} aria-label={tr("Choose a family route", "Familienroute auswählen", "Выбрать семейный маршрут")}>{conciergeCarouselItems.map((route, index) => <SwiperSlide className="booking-route-slide" key={`${route.id}-${index}`}><button type="button" className={selectedRoute === route.id ? "selected" : ""} aria-pressed={selectedRoute === route.id} onClick={() => { setSelectedRoute(route.id); routeCarousel.current?.slideTo(index); }}><img src={route.image} alt="" loading="lazy" draggable="false" /><span>{route.number}</span><div><strong>{route.name}</strong><small>{route.tagline}</small></div><i>{selectedRoute === route.id ? tr("Selected", "Ausgewählt", "Выбрано") : tr("Choose", "Auswählen", "Выбрать")}</i></button></SwiperSlide>)}</SwiperCarousel><button className="booking-route-arrow booking-route-arrow-next" type="button" onClick={() => routeCarousel.current?.slideNext()} aria-label={tr("Next route", "Nächste Route", "Следующий маршрут")}>→</button></div></div></>}
      {collection.id === "private" && <div className="booking-route-picker"><div className="booking-route-head"><div><span>{tr("Your Private route", "Ihre Private Route", "Ваш маршрут Private")}</span><strong>{tr("Choose your expedition", "Wählen Sie Ihre Expedition", "Выберите экспедицию")}</strong></div></div><div className="booking-route-carousel-shell"><button className="booking-route-arrow booking-route-arrow-prev" type="button" onClick={() => routeCarousel.current?.slidePrev()} aria-label={tr("Previous route", "Vorherige Route", "Предыдущий маршрут")}>←</button><SwiperCarousel className="booking-route-carousel" modules={[EffectCoverflow, Keyboard]} effect="coverflow" initialSlide={routeCarouselStart} centeredSlides centeredSlidesBounds={false} slidesPerView="auto" speed={850} grabCursor keyboard={{ enabled: true }} coverflowEffect={{ rotate: 0, stretch: 8, depth: 90, modifier: 1, slideShadows: false }} onSwiper={(instance) => { routeCarousel.current = instance; }} onTouchStart={(instance) => keepRouteCarouselCentered(instance)} onSliderFirstMove={(instance) => keepRouteCarouselCentered(instance)} onSlideChange={(instance) => { keepRouteCarouselCentered(instance); }} aria-label={tr("Choose a Private route", "Private Route auswählen", "Выбрать маршрут Private")}>{privateCarouselItems.map((route, index) => <SwiperSlide className="booking-route-slide" key={`${route.id}-${index}`}><button type="button" className={selectedRoute === route.id ? "selected" : ""} aria-pressed={selectedRoute === route.id} onClick={() => { choosePrivateRoute(route.id); routeCarousel.current?.slideTo(index); }}><img src={route.image} alt="" loading="lazy" decoding="async" draggable="false" /><span>{route.number}</span><div><strong>{route.name}</strong><small>({de ? route.tagline.de : ru ? route.tagline.ru : route.tagline.en})</small></div><i>{selectedRoute === route.id ? tr("Selected", "Ausgewählt", "Выбрано") : tr("Choose", "Auswählen", "Выбрать")}</i></button></SwiperSlide>)}</SwiperCarousel><button className="booking-route-arrow booking-route-arrow-next" type="button" onClick={() => routeCarousel.current?.slideNext()} aria-label={tr("Next route", "Nächste Route", "Следующий маршрут")}>→</button></div></div>}
      <div className="booking-total"><div><span>{t.total}</span><strong>{selectedPrice > 0 ? money(total) : tr("On request", "Auf Anfrage", "По запросу")}</strong></div><button className="bronze-button" onClick={pay}>{t.pay}<span>↗</span></button></div>{error && <p className="booking-error">{error}</p>}
    </div></section>
    <section className="collection-products booking-route-picker"><div className="booking-route-head"><div><span>{tr("Collection products", "Produkte der Kollektion", "Продукты коллекции")}</span><strong>{tr("Choose your journey", "Wählen Sie Ihre Reise", "Выберите путешествие")}</strong></div></div><div className="booking-route-carousel-shell"><button className="booking-route-arrow booking-route-arrow-prev" type="button" onClick={() => routeCarousel.current?.slidePrev()} aria-label={tr("Previous product", "Vorheriges Produkt", "Предыдущий продукт")}>←</button><SwiperCarousel className="booking-route-carousel" modules={[EffectCoverflow, Keyboard]} effect="coverflow" initialSlide={products.length} centeredSlides centeredSlidesBounds={false} slidesPerView="auto" speed={700} loop loopAdditionalSlides={products.length} simulateTouch grabCursor allowTouchMove threshold={10} preventClicks preventClicksPropagation keyboard={{ enabled: true }} coverflowEffect={{ rotate: 0, stretch: 8, depth: 90, modifier: 1, slideShadows: false }} onSwiper={(instance) => { routeCarousel.current = instance; }} aria-label={tr("Choose a collection product", "Produkt auswählen", "Выбрать продукт коллекции")}>{productSlides.map((product, index) => <SwiperSlide className="booking-route-slide" key={`${product.id}-${index}`}><button type="button" className={selectedRoute === product.id ? "selected" : ""} aria-pressed={selectedRoute === product.id} onClick={() => setSelectedRoute(product.id)}><img src={product.image} alt={product.name} loading="lazy" decoding="async" draggable="false" /><span>{product.number}</span><div><strong>{product.name}</strong><small>{product.description}</small></div><i>{selectedRoute === product.id ? tr("Selected", "Ausgewählt", "Выбрано") : tr("Choose", "Auswählen", "Выбрать")}</i></button></SwiperSlide>)}</SwiperCarousel><button className="booking-route-arrow booking-route-arrow-next" type="button" onClick={() => routeCarousel.current?.slideNext()} aria-label={tr("Next product", "Nächstes Produkt", "Следующий продукт")}>→</button></div></section>
    <><section className="detail-intro"><p className="section-label">{tr("Ideal for", "Ideal für", "Идеально для")}</p><p className="detail-lead">{copy.ideal}</p><div className="detail-includes"><h2>{copy.includes}</h2><ul>{(collection.id === "freedom" ? copy.signature : services).map((entry) => <li key={entry}><span>✓</span>{entry}</li>)}</ul></div>{collection.id === "freedom" && <div className="freedom-comparison"><article><h3>Freedom</h3><ul><li><span>✓</span>{tr("Motorhome", "Reisemobil", "Автодом")}</li><li><span>✓</span>{tr("Basic Road Book", "Basis-Roadbook", "Базовый путеводитель")}</li><li><span>✓</span>{tr("MLT app", "MLT App", "Приложение MLT")}</li><li><span>✓</span>{tr("Technical support", "Technischer Support", "Техническая поддержка")}</li></ul></article><article><h3>Freedom+</h3><ul><li><span>✓</span>{tr("Everything in Freedom", "Alles aus Freedom", "Всё из Freedom")}</li><li><span>✓</span>{tr("Author route", "Autorenroute", "Авторский маршрут")}</li><li><span>✓</span>{tr("Digital guide", "Digitaler Reiseführer", "Цифровой гид")}</li><li><span>✓</span>{tr("Panoramic roads", "Panoramastraßen", "Панорамные дороги")}</li><li><span>✓</span>{tr("Restaurant & location recommendations", "Restaurant- & Ortsempfehlungen", "Рекомендации ресторанов и мест")}</li><li className="freedom-supplement"><span>✓</span>+ €300–500</li></ul></article></div>}</section><section className="detail-flow"><div className="detail-flow-head"><p className="section-label">{copy.itinerary}</p><h2>{item.promise}</h2></div><div className="flow-grid">{copy.flow.map((step, index) => <article key={step.title}><span>{String(index + 1).padStart(2, "0")}</span><small>{step.label}</small><h3>{step.title}</h3><p>{step.copy}</p></article>)}</div></section></>
    <section className="detail-cta"><p className="section-label">MLT {item.name}</p><h2>{copy.cta}</h2><a className="primary-button" href="mailto:info@mlt-lifestyle.com">{t.contact}<span>↗</span></a></section>
    <footer className="light-footer"><div className="light-footer-logo"><img src="/mlt-logo.svg" alt="MLT" /><p>Individual Road Expeditions across Europe</p></div><div><strong>Explore</strong><a href="/#collections">Collections</a><a href="/#experiences">Experiences</a><a href="/plan">Smart map</a></div><div><strong>Legal</strong><a href="/legal/imprint">Imprint</a><a href="/legal/privacy">Privacy</a><a href="/legal/terms">Terms</a></div><div><strong>Contact</strong><a href="mailto:info@mlt-lifestyle.com">info@mlt-lifestyle.com</a><a href="tel:+4917632523799">+49 176 325 23 799</a></div><small>© 2026 MLT Maschinenhandel GmbH Import-Export</small></footer>
  </main>;
}
