"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Swiper as SwiperCarousel, SwiperSlide } from "swiper/react";
import type { Swiper as SwiperInstance } from "swiper";
import { EffectCoverflow, Keyboard } from "swiper/modules";
import "swiper/css";
import "swiper/css/effect-coverflow";
import { journeyRoutes, type Collection } from "../../../content/mlt";
import { collectionDe, type Locale } from "../../../content/i18n";
import { collectionDetails } from "../../../content/collection-details";

const rates = { freedom: [{ d: 7, p: 1490 }, { d: 10, p: 1990 }, { d: 14, p: 2590 }, { d: 21, p: 3690 }, { d: 30, p: 4990 }], signature: [{ d: 7, p: 2490 }, { d: 10, p: 3557 }, { d: 14, p: 4980 }, { d: 21, p: 7470 }, { d: 30, p: 10671 }], concierge: [{ d: 7, p: 4990 }, { d: 10, p: 7129 }, { d: 14, p: 9980 }, { d: 21, p: 14970 }, { d: 30, p: 21386 }], private: [{ d: 7, p: 19900 }, { d: 10, p: 28429 }, { d: 14, p: 39800 }, { d: 21, p: 59700 }, { d: 30, p: 85286 }], proposal: [{ d: 3, p: 0 }] } as const;
const freedomPlusRates: Record<number, number> = { 7: 1790, 10: 2340, 14: 3040, 21: 4190, 30: 5490 };
const hero: Record<string, string> = { freedom: "/collection-freedom-hero.png", signature: "/collection-signature-hero.png", concierge: "/collection-concierge-hero.png", private: "/collection-private-hero.png" };
const dateIso = (value: Date) => value.toISOString().slice(0, 10);
const routeCarouselCopies = 9;
const routeCarouselItems = Array.from({ length: routeCarouselCopies }, () => journeyRoutes).flat();
const routeCarouselStart = journeyRoutes.length * Math.floor(routeCarouselCopies / 2) + 3;
export function CollectionDetail({ collection }: { collection: Collection }) {
  const routeCarousel = useRef<SwiperInstance | null>(null);
  const [locale, setLocale] = useState<Locale>("en"); const options = rates[collection.id as keyof typeof rates];
  const [days, setDays] = useState(options[0].d); const [start, setStart] = useState(""); const [guests, setGuests] = useState(1); const [plus, setPlus] = useState(false); const [selectedRoute, setSelectedRoute] = useState(""); const [activeRoute, setActiveRoute] = useState(3); const [error, setError] = useState("");
  useEffect(() => { if (localStorage.getItem("mlt-locale") === "de") setLocale("de"); try { const draft = JSON.parse(localStorage.getItem("mlt-journey-draft") || "null"); const savedRoute = draft?.places?.find((id: string) => journeyRoutes.some((route) => route.id === id)); if (savedRoute) setSelectedRoute(savedRoute); } catch {} }, []);
  const item = locale === "de" ? { ...collection, ...collectionDe[collection.id] } : collection; const copy = collectionDetails[collection.id][locale]; const selected = options.find((option) => option.d === days) || options[0];
  const end = useMemo(() => { if (!start) return ""; const next = new Date(`${start}T12:00:00`); next.setDate(next.getDate() + days); return dateIso(next); }, [start, days]);
  const selectedPrice = collection.id === "freedom" && plus ? freedomPlusRates[days] : selected.p; const total = selectedPrice + Math.max(0, guests - 2) * 190; const de = locale === "de";
  const t = de ? { choose: "Reisedaten wählen", departure: "Abreise", return: "Rückgabe", guests: "Reisende", total: "Gesamt", pay: "Sicher bezahlen", error: "Bitte wählen Sie zuerst ein Abreisedatum.", contact: "Concierge kontaktieren" } : { choose: "Choose your travel dates", departure: "Departure", return: "Return", guests: "Travellers", total: "Total", pay: "Pay securely", error: "Please choose a departure date first.", contact: "Talk to a concierge" };
  const money = (value: number) => new Intl.NumberFormat(de ? "de-DE" : "en-GB", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value);
  const displayDate = (value: string) => value ? new Intl.DateTimeFormat(de ? "de-DE" : "en-GB", { day: "numeric", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00`)) : "—";
  const pay = async () => { if (!start) return setError(t.error); try { const response = await fetch("/api/payment", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider: "stripe", collection: collection.id, days, extraGuests: Math.max(0, guests - 2), freedomPlus: plus, reference: `MLT-${Date.now().toString(36).toUpperCase()}` }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); location.assign(result.url); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to start payment."); } };
  const changeLanguage = (next: Locale) => { setLocale(next); localStorage.setItem("mlt-locale", next); };
  const chooseRoute = (routeId: string) => { setSelectedRoute(routeId); const defaults = { country: "Italy", arrival: "", departure: "", guests: "2 guests", vehicle: "granduca", collection: "freedom", places: [routeId], addons: [], step: 4 }; try { const draft = JSON.parse(localStorage.getItem("mlt-journey-draft") || "{}"); localStorage.setItem("mlt-journey-draft", JSON.stringify({ ...defaults, ...draft, collection: "freedom", places: [routeId], step: Math.max(draft.step || 1, 4) })); } catch { localStorage.setItem("mlt-journey-draft", JSON.stringify(defaults)); } };
  const keepRouteCarouselCentered = (instance: SwiperInstance) => { const routeIndex = ((instance.activeIndex % journeyRoutes.length) + journeyRoutes.length) % journeyRoutes.length; if (instance.activeIndex < journeyRoutes.length * 2 || instance.activeIndex >= journeyRoutes.length * (routeCarouselCopies - 2)) instance.slideTo(journeyRoutes.length * Math.floor(routeCarouselCopies / 2) + routeIndex, 0, false); return routeIndex; };
  return <main className={`collection-page collection-${collection.id}`}>
    <header className="light-nav collection-nav"><a className="light-brand" href="/"><img src="/mlt-logo.svg" alt="MLT" /></a><nav className="light-links"><a href="/#collections">Collections</a><a href="/#experiences">Experiences</a><a href="/#smart-map">Smart map</a><a href="/#about">About</a></nav><div className="light-actions"><div className="light-language"><button className={!de ? "active" : ""} onClick={() => changeLanguage("en")}>EN</button><button className={de ? "active" : ""} onClick={() => changeLanguage("de")}>DE</button></div><a className="nav-concierge" href="mailto:concierge@mlt-travel.com">{t.contact}</a></div></header>
    <section className="collection-hero" style={{ backgroundImage: `url('${hero[collection.id]}')` }}><div className="collection-hero-shade" /><div className="collection-hero-copy"><p className="light-eyebrow"><span />MLT / {item.number}</p><h1>MLT {item.name}<br /><em>Collection</em></h1><p>{copy.manifesto}</p></div></section>
    <section className="collection-booking-band"><div className="hero-booking" aria-label={t.choose}>
      {collection.id === "freedom" && <div className="package-switch"><span>Journey type</span><div><button className={!plus ? "active" : ""} onClick={() => setPlus(false)}><b>Freedom</b><small>Independent journey</small><i>→</i></button><button className={plus ? "active" : ""} onClick={() => setPlus(true)}><b>Freedom+</b><small>Route & recommendations</small><i>→</i></button></div><ul className="package-benefits">{plus ? <><li>Everything in Freedom</li><li>Author route</li><li>Digital guide</li><li>Panoramic roads</li><li>Restaurant recommendations</li><li>Location recommendations</li><li className="package-supplement">* Supplement €300–500</li></> : <><li>Motorhome</li><li>Basic Road Book</li><li>MLT app</li><li>Technical support</li></>}</ul></div>}
      <div className="booking-main"><div className="booking-duration"><span>{t.choose}</span><div>{options.map((option) => <button key={option.d} className={days === option.d ? "active" : ""} onClick={() => setDays(option.d)}><b>{option.d} days</b><small>{option.p ? money(collection.id === "freedom" && plus ? freedomPlusRates[option.d] : option.p) : "On request"}</small></button>)}</div></div><label className="booking-date"><span>{t.departure}</span><strong className="booking-date-value">{displayDate(start)}</strong><input aria-label={t.departure} type="date" min={dateIso(new Date())} value={start} onChange={(event) => setStart(event.target.value)} /></label><div className="booking-end"><span>{t.return}</span><strong>{displayDate(end)}</strong></div><div className="guest-stepper"><span>{t.guests}</span><div><button disabled={guests <= 1} onClick={() => setGuests(Math.max(1, guests - 1))}>−</button><b>{guests}</b><button disabled={guests >= 8} onClick={() => setGuests(Math.min(8, guests + 1))}>+</button></div><small>1–2 guests included · +€190 from the 3rd guest</small></div></div>
      {collection.id === "freedom" && <div className="booking-route-picker"><div className="booking-route-head"><div><span>{de ? "Ihre Route" : "Your route"}</span><strong>{de ? "Wählen Sie Ihre Reise" : "Choose your journey"}</strong></div><div><button type="button" onClick={() => routeCarousel.current?.slidePrev()} aria-label={de ? "Vorherige Route" : "Previous route"}>←</button><b className="booking-route-count">{String(activeRoute + 1).padStart(2, "0")} / {String(journeyRoutes.length).padStart(2, "0")}</b><button type="button" onClick={() => routeCarousel.current?.slideNext()} aria-label={de ? "Nächste Route" : "Next route"}>→</button></div></div><SwiperCarousel className="booking-route-carousel" modules={[EffectCoverflow, Keyboard]} effect="coverflow" initialSlide={routeCarouselStart} centeredSlides centeredSlidesBounds={false} slidesPerView="auto" speed={850} grabCursor keyboard={{ enabled: true }} coverflowEffect={{ rotate: 0, stretch: 8, depth: 90, modifier: 1, slideShadows: false }} onSwiper={(instance) => { routeCarousel.current = instance; setActiveRoute(instance.activeIndex % journeyRoutes.length); }} onTouchStart={(instance) => keepRouteCarouselCentered(instance)} onSliderFirstMove={(instance) => keepRouteCarouselCentered(instance)} onSlideChange={(instance) => setActiveRoute(keepRouteCarouselCentered(instance))} aria-label={de ? "Routen auswählen" : "Choose a route"}>{routeCarouselItems.map((route, index) => <SwiperSlide className="booking-route-slide" key={`${route.id}-${index}`}><button type="button" className={selectedRoute === route.id ? "selected" : ""} aria-pressed={selectedRoute === route.id} onClick={() => { chooseRoute(route.id); routeCarousel.current?.slideTo(index); }}><img src={route.image} alt="" draggable="false" /><span>{route.number}</span><div><small>({de ? route.tagline.de : route.tagline.en})</small><strong>{route.name}</strong></div><i>{selectedRoute === route.id ? (de ? "Ausgewählt" : "Selected") : (de ? "Auswählen" : "Choose")}</i></button></SwiperSlide>)}</SwiperCarousel></div>}
      <div className="booking-total"><div><span>{t.total}</span><strong>{selected.p ? money(total) : "On request"}</strong></div><button className="bronze-button" onClick={pay}>{t.pay}<span>↗</span></button></div>{error && <p className="booking-error">{error}</p>}
    </div></section>
    {collection.id !== "freedom" && <><section className="detail-intro"><p className="section-label">{de ? "Ideal für" : "Ideal for"}</p><p className="detail-lead">{copy.ideal}</p><div className="detail-includes"><h2>{copy.includes}</h2><ul>{item.inclusions.map((entry) => <li key={entry}><span>✓</span>{entry}</li>)}</ul></div></section><section className="detail-flow"><div className="detail-flow-head"><p className="section-label">{copy.itinerary}</p><h2>{item.promise}</h2></div><div className="flow-grid">{copy.flow.map((step, index) => <article key={step.title}><span>{String(index + 1).padStart(2, "0")}</span><small>{step.label}</small><h3>{step.title}</h3><p>{step.copy}</p></article>)}</div></section></>}
    <section className="detail-cta"><p className="section-label">MLT {item.name}</p><h2>{copy.cta}</h2><a className="primary-button" href="mailto:concierge@mlt-travel.com">{t.contact}<span>↗</span></a></section>
    <footer className="light-footer"><div className="light-footer-logo"><img src="/mlt-logo.svg" alt="MLT" /><p>Individual Road Expeditions across Europe</p></div><div><strong>Explore</strong><a href="/#collections">Collections</a><a href="/#experiences">Experiences</a><a href="/plan">Smart map</a></div><div><strong>Legal</strong><a href="/legal/imprint">Imprint</a><a href="/legal/privacy">Privacy</a><a href="/legal/terms">Terms</a></div><div><strong>Contact</strong><a href="mailto:concierge@mlt-travel.com">concierge@mlt-travel.com</a><a href="tel:+4917632523799">+49 176 325 23 799</a></div><small>© 2026 MLT Maschinenhandel GmbH Import-Export</small></footer>
  </main>;
}
