<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8'); header('Cache-Control: no-store, max-age=0'); header('X-Content-Type-Options: nosniff');
require_once __DIR__ . '/booking.php';
$body = json_decode(file_get_contents('php://input'), true); if (!is_array($body)) $body = [];
$db = mlt_db(mlt_settings()); if (!$db) { http_response_code(503); echo json_encode(['error' => 'Account service is unavailable.']); exit; }
$action = (string)($body['action'] ?? ''); $clean = static fn($v, $n = 160) => mb_substr(trim((string)$v), 0, $n);
$token = preg_replace('/^Bearer\s+/i', '', (string)($_SERVER['HTTP_AUTHORIZATION'] ?? ''));
$userForToken = static function (PDO $db, string $token): ?array { if (!$token) return null; $q = $db->prepare('SELECT id,email,first_name,last_name,phone,locale,role FROM mlt_users WHERE session_hash = ? AND session_expires_at > NOW() LIMIT 1'); $q->execute([hash('sha256', $token)]); return $q->fetch() ?: null; };
$public = static fn(array $u) => ['id'=>(int)$u['id'],'email'=>$u['email'],'firstName'=>$u['first_name'],'lastName'=>$u['last_name'],'phone'=>$u['phone'] ?? '', 'locale'=>$u['locale'], 'role'=>$u['role'] ?? 'traveller'];
if ($action === 'register' || $action === 'login') {
  $email = strtolower($clean($body['email'] ?? '')); $password = (string)($body['password'] ?? ''); if (!filter_var($email, FILTER_VALIDATE_EMAIL) || strlen($password) < 8) { http_response_code(400); echo json_encode(['error'=>'Enter a valid email and a password of at least 8 characters.']); exit; }
  if ($action === 'register') { $first = $clean($body['firstName'] ?? '',80); $last = $clean($body['lastName'] ?? '',80); if (!$first || !$last) { http_response_code(400); echo json_encode(['error'=>'Enter your first and last name.']); exit; } try { $q=$db->prepare('INSERT INTO mlt_users (email,password_hash,first_name,last_name,phone,locale) VALUES (?,?,?,?,?,?)'); $q->execute([$email,password_hash($password,PASSWORD_DEFAULT),$first,$last,$clean($body['phone'] ?? '',80),in_array($body['locale'] ?? '', ['en','de','ru'], true) ? $body['locale'] : 'en']); } catch (Throwable $e) { http_response_code(409); echo json_encode(['error'=>'An account with this email already exists. Please sign in.']); exit; } }
  $q=$db->prepare('SELECT * FROM mlt_users WHERE email=? LIMIT 1'); $q->execute([$email]); $user=$q->fetch(); if (!$user || !password_verify($password,$user['password_hash'])) { http_response_code(401); echo json_encode(['error'=>'Incorrect email or password.']); exit; }
  $settings=mlt_settings(); $operatorRoles=is_array($settings['operator_roles'] ?? null) ? $settings['operator_roles'] : ['dahelp@yandex.com'=>'admin','mlt-concierge@mlt-lifestyle.com'=>'concierge']; $assignedRole=$operatorRoles[strtolower($user['email'])] ?? null; if(in_array($assignedRole,['admin','concierge'],true) && ($user['role'] ?? 'traveller') !== $assignedRole){$db->prepare('UPDATE mlt_users SET role=? WHERE id=?')->execute([$assignedRole,$user['id']]);$user['role']=$assignedRole;}
  $newToken=bin2hex(random_bytes(32)); $q=$db->prepare('UPDATE mlt_users SET session_hash=?,session_expires_at=DATE_ADD(NOW(), INTERVAL 30 DAY) WHERE id=?'); $q->execute([hash('sha256',$newToken),$user['id']]); echo json_encode(['ok'=>true,'token'=>$newToken,'user'=>$public($user)]); exit;
}
$user = $userForToken($db, $token); if (!$user) { http_response_code(401); echo json_encode(['error'=>'Please sign in again.']); exit; }
if ($action === 'profile') { $first=$clean($body['firstName'] ?? $user['first_name'],80); $last=$clean($body['lastName'] ?? $user['last_name'],80); $locale=in_array($body['locale'] ?? '', ['en','de','ru'],true) ? $body['locale'] : $user['locale']; $q=$db->prepare('UPDATE mlt_users SET first_name=?,last_name=?,phone=?,locale=? WHERE id=?'); $q->execute([$first,$last,$clean($body['phone'] ?? $user['phone'],80),$locale,$user['id']]); $user=array_merge($user,['first_name'=>$first,'last_name'=>$last,'phone'=>$clean($body['phone'] ?? $user['phone'],80),'locale'=>$locale]); echo json_encode(['ok'=>true,'user'=>$public($user)]); exit; }
if ($action === 'cleanup_legacy_test_orders') { $q=$db->prepare('SELECT id FROM mlt_orders WHERE (user_id=? OR customer_email=?) AND archived_at IS NULL AND LOWER(collection_name) LIKE "%freedom%" AND (total_amount=1990 OR amount=1990) ORDER BY created_at DESC LIMIT 1'); $q->execute([$user['id'],$user['email']]); $keep=(int)$q->fetchColumn(); if($keep){$db->prepare('UPDATE mlt_orders SET archived_at=NOW() WHERE (user_id=? OR customer_email=?) AND archived_at IS NULL AND id<>?')->execute([$user['id'],$user['email'],$keep]);} echo json_encode(['ok'=>true]); exit; }
if (in_array($action,['create_application','orders'],true)) { $db->prepare('UPDATE mlt_orders SET status="completed" WHERE (user_id=? OR customer_email=?) AND status="paid" AND departure_date IS NOT NULL AND departure_date<CURDATE()')->execute([$user['id'],$user['email']]); }
if ($action === 'create_application') { $q=$db->prepare('SELECT reference_code FROM mlt_orders WHERE (user_id=? OR customer_email=?) AND archived_at IS NULL AND status NOT IN ("completed","cancelled") ORDER BY created_at DESC LIMIT 1'); $q->execute([$user['id'],$user['email']]); $existing=$q->fetchColumn(); if($existing){echo json_encode(['ok'=>true,'created'=>false,'reference'=>$existing]);exit;} $collection=strtolower($clean($body['collection'] ?? '',30)); $days=(int)($body['days'] ?? 0); $guests=max(1,min(8,(int)($body['guests'] ?? 1))); $prices=['freedom'=>[7=>1490,10=>1990,14=>2590,21=>3690,30=>4990],'signature'=>[7=>2490,10=>4290,14=>5890],'concierge'=>[7=>4990,10=>6590,14=>8990],'private'=>[7=>19900,10=>28429,14=>39800,21=>59700,30=>85286]]; $base=$prices[$collection][$days] ?? 0; if($collection==='freedom'&&!empty($body['freedomPlus']))$base=[7=>1790,10=>2340,14=>3040,21=>4190,30=>5490][$days]??0; if($collection==='signature'&&!empty($body['signatureTailored']))$base=[7=>2990,10=>4290,14=>5890][$days]??0; if(!$base){http_response_code(400);echo json_encode(['error'=>'Invalid journey selection.']);exit;} $total=$base+max(0,$guests-2)*190; $reference='MLT-'.strtoupper(substr(base_convert((string)round(microtime(true)*1000),10,36),-8)); mlt_create_order($db,$reference,['collection'=>$collection,'country'=>$clean($body['country'] ?? '',80),'days'=>$days,'arrival'=>$clean($body['arrival'] ?? '',20),'departure'=>$clean($body['departure'] ?? '',20),'guests'=>(string)$guests,'vehicle'=>$clean($body['vehicle'] ?? 'MLT motorhome',120),'route'=>[$clean($body['route'] ?? '',160)],'extras'=>is_array($body['tailoredInterests'] ?? null)?$body['tailoredInterests']:[],'notes'=>'Account application'],['firstName'=>$user['first_name'],'lastName'=>$user['last_name'],'email'=>$user['email'],'phone'=>$user['phone'] ?? '']); $db->prepare('UPDATE mlt_orders SET total_amount=? WHERE reference_code=?')->execute([$total,$reference]); echo json_encode(['ok'=>true,'created'=>true,'reference'=>$reference]);exit; }
if ($action === 'orders') { $q=$db->prepare('SELECT reference_code,status,payment_provider,amount,total_amount,paid_amount,currency,collection_name,vehicle_name,country_name,guests,travel_days,arrival_date,departure_date,route_json,extras_json,notes,created_at,paid_at FROM mlt_orders WHERE (user_id=? OR customer_email=?) AND archived_at IS NULL ORDER BY created_at DESC'); $q->execute([$user['id'],$user['email']]); echo json_encode(['ok'=>true,'user'=>$public($user),'orders'=>$q->fetchAll()]); exit; }
if ($action === 'order') { $reference=$clean($body['reference'] ?? '',80); $q=$db->prepare('SELECT reference_code,status,payment_provider,amount,currency,collection_name,vehicle_name,country_name,guests,travel_days,arrival_date,departure_date,route_json,extras_json,notes,created_at,paid_at FROM mlt_orders WHERE reference_code=? AND (user_id=? OR customer_email=?) AND archived_at IS NULL LIMIT 1'); $q->execute([$reference,$user['id'],$user['email']]); $order=$q->fetch(); if(!$order){http_response_code(404);echo json_encode(['error'=>'Application not found.']);exit;} echo json_encode(['ok'=>true,'order'=>$order]); exit; }
if ($action === 'select_order') { $reference=$clean($body['reference'] ?? '',80); $q=$db->prepare('SELECT id,total_amount,amount,paid_amount,status FROM mlt_orders WHERE reference_code=? AND (user_id=? OR customer_email=?) AND archived_at IS NULL LIMIT 1'); $q->execute([$reference,$user['id'],$user['email']]); $order=$q->fetch(); $total=$order ? max((float)($order['total_amount'] ?? 0),(float)($order['amount'] ?? 0)) : 0; if(!$order || $total<=0 || in_array($order['status'],['paid','completed','cancelled'],true) || (float)($order['paid_amount'] ?? 0)+0.009>=$total){http_response_code(400);echo json_encode(['error'=>'This application cannot be selected for payment.']);exit;} $db->prepare('UPDATE mlt_orders SET status="requested" WHERE user_id=? AND status="selected"')->execute([$user['id']]); $db->prepare('UPDATE mlt_orders SET status="selected" WHERE id=?')->execute([$order['id']]); echo json_encode(['ok'=>true]); exit; }
if ($action === 'archive') { $reference=$clean($body['reference'] ?? '',80); $q=$db->prepare('UPDATE mlt_orders SET archived_at=NOW() WHERE reference_code=? AND (user_id=? OR customer_email=?) AND archived_at IS NULL'); $q->execute([$reference,$user['id'],$user['email']]); echo json_encode(['ok'=>true]); exit; }
echo json_encode(['ok'=>true,'user'=>$public($user)]);
