<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8'); header('Cache-Control: no-store, max-age=0');
require_once __DIR__ . '/booking.php';
$body=json_decode(file_get_contents('php://input'),true);if(!is_array($body))$body=[];
$db=mlt_db(mlt_settings());if(!$db){http_response_code(503);echo json_encode(['error'=>'Catalog service unavailable.']);exit;}
$db->exec('CREATE TABLE IF NOT EXISTS mlt_catalog_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, item_type VARCHAR(24) NOT NULL, collection_id VARCHAR(48) NULL, slug VARCHAR(100) NOT NULL UNIQUE, title VARCHAR(180) NOT NULL, subtitle VARCHAR(255) NULL, image_path VARCHAR(255) NULL, price DECIMAL(12,2) NULL, currency CHAR(3) NOT NULL DEFAULT "EUR", points_json TEXT NULL, data_json TEXT NULL, sort_order SMALLINT NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX catalog_type_collection (item_type,collection_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
$seed=[
 ['collection',null,'freedom','MLT Freedom Collection','Self-directed discovery','/collection-freedom.webp',1490,1],['collection',null,'signature','MLT Signature Collection','Curated, end to end','/collection-signature.webp',2490,2],['collection',null,'concierge','MLT Concierge Collection','Always one step ahead','/collection-concierge.webp',4990,3],['collection',null,'private','MLT Private Collection','The rarest way to move','/collection-private.webp',19900,4],
];
$routes=[
 'freedom'=>[['dolomites-grand-tour','Dolomites Freedom Journey','/route-dolomites.jpg'],['lakes-of-bavaria','Bavaria Discovery Pass','/route-bavaria.jpg'],['alpine-escape','Alpine Escape Express','/route-alpine.jpg'],['wine-roads-collection','Wine Roads Horizon','/route-wine-roads.jpg'],['mediterranean-discovery','Mediterranean Coastline','/route-mediterranean.jpg'],['winter-alps-expedition','Winter Alps Horizon','/route-winter-alps.jpg'],['black-forest-experience','Black Forest Trail','/route-black-forest.jpg']],
 'signature'=>[['signature-dolomites','Dolomites Signature Route','/signature-route-dolomites.jpg'],['signature-bavaria','Bavaria Signature Experience','/signature-route-bavaria.jpg'],['signature-alpine','Alpine Escape Signature','/signature-route-alpine.jpg'],['signature-wine','Wine Roads Signature Cellars','/signature-route-wine.jpg'],['signature-mediterranean','Mediterranean Signature Riviera','/signature-route-mediterranean.jpg'],['signature-winter','Winter Alps Signature','/signature-route-winter.jpg'],['signature-black-forest','Black Forest Signature Retreat','/signature-route-black-forest.jpg']],
 'concierge'=>[['family-dolomites','Family Dolomites Expedition','/concierge-family-dolomites.jpg'],['family-bavaria','Bavaria Family Tales & Lakes','/concierge-family-bavaria.jpg'],['family-alpine','Alpine Family Sanctuary','/concierge-family-alpine.jpg'],['family-wine','Wine Roads Family Estates','/concierge-family-wine.jpg'],['family-mediterranean','Mediterranean Family Riviera','/concierge-family-mediterranean.jpg'],['family-winter','Winter Alps Family Wonderland','/concierge-family-winter.jpg'],['family-black-forest','Black Forest Family Forest & Lore','/concierge-family-black-forest.jpg']],
 'private'=>[['private-dolomites','Dolomites Grand Tour','/private-route-dolomites.webp'],['private-bavaria','Lakes of Bavaria','/private-route-bavaria.webp'],['private-alpine','Alpine Escape','/private-route-alpine.webp'],['private-wine','Wine Roads Collection','/private-route-wine.webp'],['private-mediterranean','Mediterranean Discovery','/private-route-mediterranean.webp'],['private-winter','Winter Alps Expedition','/private-route-winter.webp'],['private-black-forest','Black Forest Experience','/private-route-black-forest.webp']],
];
$extras=[['helicopter','Private helicopter tours','/experience-heli.jpg'],['wine','Private wine tastings','/experience-wine.jpg'],['chef','Private chef experience','/experience-chef.jpg'],['yacht','Luxury yacht charter','/experience-yacht.jpg'],['transfer','VIP airport transfer','/experience-transfer.jpg'],['photography','Private photographer','/experience-photo.jpg']];
if(!(int)$db->query('SELECT COUNT(*) FROM mlt_catalog_items')->fetchColumn()){ $insert=$db->prepare('INSERT INTO mlt_catalog_items(item_type,collection_id,slug,title,subtitle,image_path,price,sort_order) VALUES(?,?,?,?,?,?,?,?)');foreach($seed as $item)$insert->execute($item);foreach($routes as $collection=>$items)foreach($items as $index=>$item)$insert->execute(['product',$collection,$item[0],$item[1],null,$item[2],null,$index+1]);foreach($extras as $index=>$item)$insert->execute(['extra',null,$item[0],$item[1],null,$item[2],null,$index+1]);}
$token=preg_replace('/^Bearer\s+/i','',(string)($_SERVER['HTTP_AUTHORIZATION']??''));$q=$db->prepare('SELECT id,role FROM mlt_users WHERE session_hash=? AND session_expires_at>NOW() LIMIT 1');$q->execute([hash('sha256',$token)]);$operator=$q->fetch();$action=(string)($body['action']??'list');
if($action==='list'){echo json_encode(['ok'=>true,'items'=>$db->query('SELECT * FROM mlt_catalog_items ORDER BY item_type,collection_id,sort_order,title')->fetchAll(),'canEdit'=>($operator['role']??'')==='admin']);exit;}
if(($operator['role']??'')!=='admin'){http_response_code(403);echo json_encode(['error'=>'Administrator access required.']);exit;}
if($action==='save'){$id=(int)($body['id']??0);$type=in_array($body['itemType']??'',['collection','product','route','extra'],true)?$body['itemType']:'';$slug=preg_replace('/[^a-z0-9-]/','',strtolower((string)($body['slug']??'')));$title=mb_substr(trim((string)($body['title']??'')),0,180);if(!$type||!$slug||!$title){http_response_code(400);echo json_encode(['error'=>'Type, slug and title are required.']);exit;}$values=[(string)($body['collectionId']??'')?:null,$slug,$title,mb_substr(trim((string)($body['subtitle']??'')),0,255)?:null,mb_substr(trim((string)($body['imagePath']??'')),0,255)?:null,is_numeric($body['price']??null)?(float)$body['price']:null,json_encode(is_array($body['points']??null)?$body['points']:[],JSON_UNESCAPED_UNICODE),(int)($body['sortOrder']??0),(int)!empty($body['active'])];if($id){$u=$db->prepare('UPDATE mlt_catalog_items SET collection_id=?,slug=?,title=?,subtitle=?,image_path=?,price=?,points_json=?,sort_order=?,is_active=? WHERE id=?');$u->execute([...$values,$id]);}else{$u=$db->prepare('INSERT INTO mlt_catalog_items(collection_id,slug,title,subtitle,image_path,price,points_json,sort_order,is_active,item_type) VALUES(?,?,?,?,?,?,?,?,?,?)');$u->execute([...$values,$type]);}echo json_encode(['ok'=>true]);exit;}
echo json_encode(['error'=>'Unknown action']);
