<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8'); header('Cache-Control: no-store, max-age=0');
require_once __DIR__ . '/booking.php';
$body=json_decode(file_get_contents('php://input'),true);if(!is_array($body))$body=[];
$db=mlt_db(mlt_settings());if(!$db){http_response_code(503);echo json_encode(['error'=>'Catalog service unavailable.']);exit;}
$db->exec('CREATE TABLE IF NOT EXISTS mlt_catalog_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, item_type VARCHAR(24) NOT NULL, collection_id VARCHAR(48) NULL, slug VARCHAR(100) NOT NULL UNIQUE, title VARCHAR(180) NOT NULL, subtitle VARCHAR(255) NULL, image_path VARCHAR(255) NULL, price DECIMAL(12,2) NULL, currency CHAR(3) NOT NULL DEFAULT "EUR", points_json TEXT NULL, data_json TEXT NULL, sort_order SMALLINT NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX catalog_type_collection (item_type,collection_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
foreach(['days_from SMALLINT NULL','days_to SMALLINT NULL','price_to DECIMAL(12,2) NULL'] as $column){try{$db->exec("ALTER TABLE mlt_catalog_items ADD COLUMN $column");}catch(Throwable $e){}}
$db->exec('CREATE TABLE IF NOT EXISTS mlt_route_points (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(100) NOT NULL UNIQUE, title VARCHAR(180) NOT NULL, country_name VARCHAR(100) NULL, latitude DECIMAL(10,7) NULL, longitude DECIMAL(10,7) NULL, description TEXT NULL, image_path VARCHAR(255) NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
$seed=[
 ['collection',null,'freedom','MLT Freedom Collection','Self-directed discovery','/collection-freedom.webp',1490,1],['collection',null,'signature','MLT Signature Collection','Curated, end to end','/collection-signature.webp',2490,2],['collection',null,'concierge','MLT Concierge Collection','Always one step ahead','/collection-concierge.webp',4990,3],['collection',null,'private','MLT Private Collection','The rarest way to move','/collection-private.webp',19900,4],
];
$routes=[
 'freedom'=>[['dolomites-grand-tour','Dolomites Freedom Journey','/route-dolomites.jpg'],['lakes-of-bavaria','Bavaria Discovery Pass','/route-bavaria.jpg'],['alpine-escape','Alpine Escape Express','/route-alpine.jpg'],['wine-roads-collection','Wine Roads Horizon','/route-wine-roads.jpg'],['mediterranean-discovery','Mediterranean Coastline','/route-mediterranean.jpg'],['winter-alps-expedition','Winter Alps Horizon','/route-winter-alps.jpg'],['black-forest-experience','Black Forest Trail','/route-black-forest.jpg']],
 'signature'=>[['signature-dolomites','Dolomites Signature Route','/signature-route-dolomites.jpg'],['signature-bavaria','Bavaria Signature Experience','/signature-route-bavaria.jpg'],['signature-alpine','Alpine Escape Signature','/signature-route-alpine.jpg'],['signature-wine','Wine Roads Signature Cellars','/signature-route-wine.jpg'],['signature-mediterranean','Mediterranean Signature Riviera','/signature-route-mediterranean.jpg'],['signature-winter','Winter Alps Signature','/signature-route-winter.jpg'],['signature-black-forest','Black Forest Signature Retreat','/signature-route-black-forest.jpg']],
 'concierge'=>[['family-dolomites','Family Dolomites Expedition','/concierge-family-dolomites.jpg'],['family-bavaria','Bavaria Family Tales & Lakes','/concierge-family-bavaria.jpg'],['family-alpine','Alpine Family Sanctuary','/concierge-family-alpine.jpg'],['family-wine','Wine Roads Family Estates','/concierge-family-wine.jpg'],['family-mediterranean','Mediterranean Family Riviera','/concierge-family-mediterranean.jpg'],['family-winter','Winter Alps Family Wonderland','/concierge-family-winter.jpg'],['family-black-forest','Black Forest Family Forest & Lore','/concierge-family-black-forest.jpg']],
 'private'=>[['private-dolomites','Dolomites Grand Tour','/private-route-dolomites.webp'],['private-bavaria','Lakes of Bavaria','/private-route-bavaria.webp'],['private-alpine','Alpine Escape','/private-route-alpine.webp'],['private-wine','Wine Roads Collection','/private-route-wine.webp'],['private-mediterranean','Mediterranean Discovery','/private-route-mediterranean.webp'],['private-winter','Winter Alps Expedition','/private-route-winter.webp'],['private-black-forest','Black Forest Experience','/private-route-black-forest.webp']],
];
$extras=[['helicopter','Private helicopter tours','/experience-heli.jpg'],['wine','Private wine tastings','/experience-wine.jpg'],['chef','Private chef experience','/experience-chef.jpg'],['yacht','Luxury yacht charter','/experience-yacht.jpg'],['transfer','VIP airport transfer','/experience-transfer.jpg'],['photography','Private photographer','/experience-photo.jpg']];
if(!(int)$db->query('SELECT COUNT(*) FROM mlt_catalog_items')->fetchColumn()){ $insert=$db->prepare('INSERT INTO mlt_catalog_items(item_type,collection_id,slug,title,subtitle,image_path,price,sort_order) VALUES(?,?,?,?,?,?,?,?)');foreach($seed as $item)$insert->execute($item);foreach($routes as $collection=>$items)foreach($items as $index=>$item)$insert->execute(['product',$collection,$item[0],$item[1],null,$item[2],null,$index+1]);foreach($extras as $index=>$item)$insert->execute(['extra',null,$item[0],$item[1],null,$item[2],null,$index+1]);}
$knownRanges=['freedom'=>[7,30,1490,4990],'signature'=>[7,14,2490,5890],'concierge'=>[7,14,4990,8990],'private'=>[7,21,19900,59700]];
foreach($knownRanges as $knownSlug=>$range){$fill=$db->prepare('UPDATE mlt_catalog_items SET days_from=COALESCE(days_from,?),days_to=COALESCE(days_to,?),price=COALESCE(price,?),price_to=COALESCE(price_to,?) WHERE item_type="collection" AND slug=?');$fill->execute([$range[0],$range[1],$range[2],$range[3],$knownSlug]);}
$knownPricing=['freedom'=>[[7,1490],[10,1990],[14,2590],[21,3690],[30,4990]],'signature'=>[[7,2490],[10,4290],[14,5890]],'concierge'=>[[7,4990],[10,6590],[14,8990]],'private'=>[[7,19900],[10,28429],[14,39800],[21,59700]]];
foreach($knownPricing as $knownSlug=>$rows){$fill=$db->prepare('UPDATE mlt_catalog_items SET data_json=? WHERE item_type="collection" AND slug=? AND (data_json IS NULL OR data_json="")');$fill->execute([json_encode(['pricing'=>array_map(fn($row)=>['days'=>$row[0],'price'=>$row[1]],$rows)],JSON_UNESCAPED_UNICODE),$knownSlug]);}
$token=preg_replace('/^Bearer\s+/i','',(string)($_SERVER['HTTP_AUTHORIZATION']??''));$q=$db->prepare('SELECT id,role FROM mlt_users WHERE session_hash=? AND session_expires_at>NOW() LIMIT 1');$q->execute([hash('sha256',$token)]);$operator=$q->fetch();$action=(string)($body['action']??'list');
if($action==='list'){echo json_encode(['ok'=>true,'items'=>$db->query('SELECT * FROM mlt_catalog_items ORDER BY item_type,collection_id,sort_order,title')->fetchAll(),'points'=>$db->query('SELECT * FROM mlt_route_points ORDER BY country_name,title')->fetchAll(),'canEdit'=>($operator['role']??'')==='admin']);exit;}
if(($operator['role']??'')!=='admin'){http_response_code(403);echo json_encode(['error'=>'Administrator access required.']);exit;}
if($action==='upload'){$raw=(string)($body['file']??'');if(!preg_match('#^data:image/(webp|avif);base64,(.+)$#s',$raw,$m)){http_response_code(400);echo json_encode(['error'=>'Only WebP and AVIF images are accepted.']);exit;}$bytes=base64_decode($m[2],true);if($bytes===false||strlen($bytes)>8*1024*1024){http_response_code(400);echo json_encode(['error'=>'Image is invalid or exceeds 8 MB.']);exit;}$detected=(new finfo(FILEINFO_MIME_TYPE))->buffer($bytes);$allowed=['image/webp'=>'webp','image/avif'=>'avif'];if(!isset($allowed[$detected])){http_response_code(400);echo json_encode(['error'=>'The uploaded file is not a valid WebP or AVIF image.']);exit;}$dir=dirname(__DIR__).'/uploads/catalog';if(!is_dir($dir)&&!mkdir($dir,0755,true)){http_response_code(500);echo json_encode(['error'=>'Upload directory is unavailable.']);exit;}$name=bin2hex(random_bytes(12)).'.'.$allowed[$detected];if(file_put_contents($dir.'/'.$name,$bytes)===false){http_response_code(500);echo json_encode(['error'=>'Could not save image.']);exit;}echo json_encode(['ok'=>true,'path'=>'/uploads/catalog/'.$name]);exit;}
if($action==='save'){
 $id=(int)($body['id']??0);$type=in_array($body['itemType']??'',['collection','product','route','extra'],true)?$body['itemType']:'';$slug=preg_replace('/[^a-z0-9-]/','',strtolower((string)($body['slug']??'')));$title=mb_substr(trim((string)($body['title']??'')),0,180);
 if(!$type||!$slug||!$title){http_response_code(400);echo json_encode(['error'=>'Type, slug and title are required.']);exit;}
 $pricing=[];
 if($type==='collection'){
  foreach(is_array($body['pricing']??null)?$body['pricing']:[] as $row){$days=(int)($row['days']??0);$amount=is_numeric($row['price']??null)?(float)$row['price']:-1;if($days<1||$amount<0||isset($pricing[$days])){http_response_code(400);echo json_encode(['error'=>'Each collection rate needs unique days and a valid price.']);exit;}$pricing[$days]=['days'=>$days,'price'=>$amount];}
  if(!$pricing){http_response_code(400);echo json_encode(['error'=>'Add at least one collection rate.']);exit;}ksort($pricing);$pricing=array_values($pricing);
 }
 $prices=array_column($pricing,'price');$days=array_column($pricing,'days');
 $price=$pricing?min($prices):(is_numeric($body['price']??null)?(float)$body['price']:null);$priceTo=$pricing?max($prices):(is_numeric($body['priceTo']??null)?(float)$body['priceTo']:null);$daysFrom=$pricing?min($days):(is_numeric($body['daysFrom']??null)?(int)$body['daysFrom']:null);$daysTo=$pricing?max($days):(is_numeric($body['daysTo']??null)?(int)$body['daysTo']:null);
 $dataJson=$pricing?json_encode(['pricing'=>$pricing],JSON_UNESCAPED_UNICODE):null;
 $values=[(string)($body['collectionId']??'')?:null,$slug,$title,mb_substr(trim((string)($body['subtitle']??'')),0,255)?:null,mb_substr(trim((string)($body['imagePath']??'')),0,255)?:null,$price,$priceTo,$daysFrom,$daysTo,json_encode(is_array($body['points']??null)?$body['points']:[],JSON_UNESCAPED_UNICODE),$dataJson,(int)($body['sortOrder']??0),(int)!empty($body['active'])];
 if($id){$u=$db->prepare('UPDATE mlt_catalog_items SET collection_id=?,slug=?,title=?,subtitle=?,image_path=?,price=?,price_to=?,days_from=?,days_to=?,points_json=?,data_json=COALESCE(?,data_json),sort_order=?,is_active=? WHERE id=?');$u->execute([...$values,$id]);}
 else{$u=$db->prepare('INSERT INTO mlt_catalog_items(collection_id,slug,title,subtitle,image_path,price,price_to,days_from,days_to,points_json,data_json,sort_order,is_active,item_type) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$u->execute([...$values,$type]);}
 echo json_encode(['ok'=>true]);exit;
}
if($action==='save_point'){$id=(int)($body['id']??0);$slug=preg_replace('/[^a-z0-9-]/','',strtolower((string)($body['slug']??'')));$title=mb_substr(trim((string)($body['title']??'')),0,180);if(!$slug||!$title){http_response_code(400);echo json_encode(['error'=>'Point title and slug are required.']);exit;}$v=[$slug,$title,mb_substr(trim((string)($body['country']??'')),0,100)?:null,is_numeric($body['latitude']??null)?(float)$body['latitude']:null,is_numeric($body['longitude']??null)?(float)$body['longitude']:null,mb_substr(trim((string)($body['description']??'')),0,2000)?:null,mb_substr(trim((string)($body['imagePath']??'')),0,255)?:null,(int)!empty($body['active'])];if($id){$q=$db->prepare('UPDATE mlt_route_points SET slug=?,title=?,country_name=?,latitude=?,longitude=?,description=?,image_path=?,is_active=? WHERE id=?');$q->execute([...$v,$id]);}else{$q=$db->prepare('INSERT INTO mlt_route_points(slug,title,country_name,latitude,longitude,description,image_path,is_active) VALUES(?,?,?,?,?,?,?,?)');$q->execute($v);}echo json_encode(['ok'=>true]);exit;}
echo json_encode(['error'=>'Unknown action']);
