<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8'); header('Cache-Control: no-store, max-age=0');
require_once __DIR__ . '/booking.php';
$body=json_decode(file_get_contents('php://input'),true); if(!is_array($body))$body=[];
$db=mlt_db(mlt_settings()); if(!$db){http_response_code(503);echo json_encode(['error'=>'Concierge service unavailable.']);exit;}
$token=preg_replace('/^Bearer\s+/i','',(string)($_SERVER['HTTP_AUTHORIZATION']??''));
$q=$db->prepare('SELECT id,email,first_name,last_name,role FROM mlt_users WHERE session_hash=? AND session_expires_at>NOW() LIMIT 1');$q->execute([hash('sha256',$token)]);$operator=$q->fetch();
if(!$operator||!in_array($operator['role']??'traveller',['concierge','admin'],true)){http_response_code(403);echo json_encode(['error'=>'Concierge access required.']);exit;}
$action=(string)($body['action']??'overview');
if($action==='overview'){$orders=$db->query('SELECT reference_code,status,payment_provider,amount,total_amount,paid_amount,extras_amount,currency,first_name,last_name,customer_email,phone,collection_name,country_name,guests,travel_days,arrival_date,departure_date,route_json,route_points_json,extras_json,service_items_json,client_note,concierge_note,created_at,paid_at FROM mlt_orders WHERE archived_at IS NULL ORDER BY created_at DESC LIMIT 100')->fetchAll();$summary=$db->query('SELECT COUNT(*) total, SUM(status="paid") paid, SUM(status<>"paid") pending, COALESCE(SUM(CASE WHEN status="paid" THEN amount ELSE 0 END),0) revenue FROM mlt_orders WHERE archived_at IS NULL')->fetch();echo json_encode(['ok'=>true,'operator'=>['name'=>$operator['first_name'].' '.$operator['last_name'],'role'=>$operator['role']],'summary'=>$summary,'orders'=>$orders]);exit;}
if($action==='team') {if(($operator['role']??'')!=='admin'){http_response_code(403);echo json_encode(['error'=>'Administrator access required.']);exit;}$team=$db->query("SELECT first_name,last_name,email,role,created_at FROM mlt_users WHERE role IN ('admin','concierge') ORDER BY role DESC, first_name, last_name")->fetchAll();echo json_encode(['ok'=>true,'team'=>$team]);exit;}
if($action==='status'){$reference=mb_substr(trim((string)($body['reference']??'')),0,80);$status=(string)($body['status']??'');$allowed=['requested','in_progress','confirmed','paid','completed','cancelled'];if(!preg_match('/^MLT-[A-Z0-9-]+$/',$reference)||!in_array($status,$allowed,true)){http_response_code(400);echo json_encode(['error'=>'Invalid application update.']);exit;}$u=$db->prepare('UPDATE mlt_orders SET status=? WHERE reference_code=?');$u->execute([$status,$reference]);echo json_encode(['ok'=>true]);exit;}
if($action==='journey_update'){$reference=mb_substr(trim((string)($body['reference']??'')),0,80);if(!preg_match('/^MLT-[A-Z0-9-]+$/',$reference)){http_response_code(400);echo json_encode(['error'=>'Invalid application.']);exit;}$cleanList=function($items,$limit){$out=[];foreach(is_array($items)?$items:[] as $item){$value=mb_substr(trim((string)$item),0,$limit);if($value!=='')$out[]=$value;}return array_values(array_unique($out));};$route=$cleanList($body['route']??[],160);$points=$cleanList($body['points']??[],180);$services=[];$extra=0.0;foreach(is_array($body['services']??null)?$body['services']:[] as $service){if(!is_array($service))continue;$title=mb_substr(trim((string)($service['title']??'')),0,120);$price=max(0,min(100000,(float)($service['price']??0)));if($title==='')continue;$services[]=['title'=>$title,'price'=>$price];$extra+=$price;}$note=mb_substr(trim((string)($body['conciergeNote']??'')),0,2000);$q=$db->prepare('SELECT total_amount,amount,extras_amount FROM mlt_orders WHERE reference_code=? AND archived_at IS NULL LIMIT 1');$q->execute([$reference]);$order=$q->fetch();if(!$order){http_response_code(404);echo json_encode(['error'=>'Application not found.']);exit;}$total=max(0,(float)($order['total_amount']??$order['amount']??0)-(float)($order['extras_amount']??0)+$extra);$u=$db->prepare('UPDATE mlt_orders SET route_json=?,route_points_json=?,service_items_json=?,extras_json=?,extras_amount=?,total_amount=?,concierge_note=? WHERE reference_code=?');$u->execute([json_encode($route,JSON_UNESCAPED_UNICODE),json_encode($points,JSON_UNESCAPED_UNICODE),json_encode($services,JSON_UNESCAPED_UNICODE),json_encode(array_map(fn($s)=>$s['title'],$services),JSON_UNESCAPED_UNICODE),$extra,$total,$note?:null,$reference]);echo json_encode(['ok'=>true,'total'=>$total]);exit;}
if($action==='payment_reminder'){$reference=mb_substr(trim((string)($body['reference']??'')),0,80);$q=$db->prepare('SELECT customer_email,first_name,total_amount,amount,paid_amount,currency,status FROM mlt_orders WHERE reference_code=? AND archived_at IS NULL LIMIT 1');$q->execute([$reference]);$order=$q->fetch();$total=(float)($order['total_amount']??$order['amount']??0);$due=max(0,$total-(float)($order['paid_amount']??0));if(!$order||$due<0.01||in_array($order['status'],['cancelled','completed'],true)){http_response_code(400);echo json_encode(['error'=>'This application does not need a reminder.']);exit;}$subject='MLT — payment reminder';$message="Hello {$order['first_name']},\n\nA remaining balance of ".number_format($due,2,'.','')." {$order['currency']} is awaiting payment for your MLT journey. Please sign in to your private account to continue.\n\nMLT Concierge";@mail($order['customer_email'],$subject,$message,"Content-Type: text/plain; charset=UTF-8");echo json_encode(['ok'=>true,'due'=>$due]);exit;}
echo json_encode(['ok'=>true]);
