"use client";

import { useEffect, useMemo, useState } from "react";
import { collections, experiences, fleet, mapPoints } from "../../content/mlt";
import { collectionDe, type Locale } from "../../content/i18n";
import RealRouteMap from "./RealRouteMap";

const copy = {
  en: { title: "Design your expedition", subtitle: "Six considered steps. One journey entirely your own.", steps: ["Journey", "Motorhome", "Collection", "Route", "Experiences", "Details"], next: "Continue", back: "Back", dates: "When would you like to travel?", country: "Starting country", arrival: "Arrival", departure: "Departure", guests: "Travellers", chooseVehicle: "Choose your travelling residence", chooseCollection: "How would you like to be supported?", chooseRoute: "Select the places that move you", chooseExperiences: "Add something extraordinary", details: "Where should your concierge reach you?", optional: "Optional — your concierge can refine this later", selected: "selected", summary: "Your expedition", submit: "Send to MLT Concierge", sending: "Sending securely...", success: "Your journey has begun.", successCopy: "Your private request has been prepared for the MLT Concierge Desk.", return: "Return to MLT", name: "Full name", email: "Email", phone: "Phone", notes: "Anything we should know?", consent: "I agree that MLT may use these details to prepare and discuss my travel proposal.", from: "From", duration: "Duration", demo: "Telegram demo channel prepared", delivered: "Delivered to Telegram Concierge Desk" },
  de: { title: "Expedition gestalten", subtitle: "Sechs durchdachte Schritte. Eine Reise ganz für Sie.", steps: ["Reise", "Reisemobil", "Kollektion", "Route", "Erlebnisse", "Kontakt"], next: "Weiter", back: "Zurück", dates: "Wann möchten Sie reisen?", country: "Startland", arrival: "Anreise", departure: "Abreise", guests: "Reisende", chooseVehicle: "Wählen Sie Ihre Residenz auf Reisen", chooseCollection: "Wie möchten Sie begleitet werden?", chooseRoute: "Wählen Sie Orte, die Sie bewegen", chooseExperiences: "Fügen Sie etwas Außergewöhnliches hinzu", details: "Wie darf Ihr Concierge Sie erreichen?", optional: "Optional — Ihr Concierge kann dies später verfeinern", selected: "ausgewählt", summary: "Ihre Expedition", submit: "An MLT Concierge senden", sending: "Wird sicher gesendet...", success: "Ihre Reise hat begonnen.", successCopy: "Ihre private Anfrage wurde für den MLT Concierge Desk vorbereitet.", return: "Zurück zu MLT", name: "Vollständiger Name", email: "E-Mail", phone: "Telefon", notes: "Was sollten wir wissen?", consent: "Ich stimme zu, dass MLT diese Angaben zur Vorbereitung und Besprechung meines Reiseangebots verwendet.", from: "Ab", duration: "Dauer", demo: "Telegram-Demokanal vorbereitet", delivered: "An Telegram Concierge Desk übermittelt" },
} as const;

const dailyRates: Record<string, [number, number]> = { freedom: [150, 220], signature: [250, 400], concierge: [450, 700], private: [2000, 4000] };
const formatEuro = (value: number, locale: Locale) => new Intl.NumberFormat(locale === "de" ? "de-DE" : "en-GB", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value);

export default function PlanPage() {
  const [locale, setLocale] = useState<Locale>("en");
  const [step, setStep] = useState(1);
  const [country, setCountry] = useState("Italy"); const [arrival, setArrival] = useState("2026-09-17"); const [departure, setDeparture] = useState("2026-09-27"); const [guests, setGuests] = useState("2 guests");
  const [vehicle, setVehicle] = useState("granduca"); const [collection, setCollection] = useState("signature"); const [places, setPlaces] = useState<string[]>(["dolomites", "como"]); const [addons, setAddons] = useState<string[]>([]);
  const [mapCountry, setMapCountry] = useState("All");
  const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(""); const [reference, setReference] = useState(""); const [delivery, setDelivery] = useState("demo");
  const t = copy[locale];
  const localizedCollections = useMemo(() => collections.map((item) => locale === "de" ? { ...item, ...collectionDe[item.id] } : item), [locale]);
  const selectedVehicle = fleet.find((item) => item.id === vehicle)!; const selectedCollection = localizedCollections.find((item) => item.id === collection)!;
  const duration = useMemo(() => arrival && departure ? Math.max(1, Math.round((new Date(departure).getTime() - new Date(arrival).getTime()) / 86400000)) : 0, [arrival, departure]);
  const estimate = useMemo(() => { const range = dailyRates[collection] || [0, 0]; return [range[0] * duration, range[1] * duration] as const; }, [collection, duration]);

  useEffect(() => { const saved = localStorage.getItem("mlt-locale"); if (saved === "de") setLocale("de"); const query = new URLSearchParams(location.search); const v = query.get("vehicle"); const c = query.get("collection"); const start = query.get("country"); const party = query.get("guests"); if (fleet.some((item) => item.id === v)) setVehicle(v!); if (collections.some((item) => item.id === c)) setCollection(c!); if (["Italy", "Austria", "Germany"].includes(start || "")) setCountry(start!); if (["2 guests", "3 guests", "4 guests", "5+ guests"].includes(party || "")) setGuests(party!); }, []);
  const toggle = (value: string, values: string[], setter: (next: string[]) => void) => setter(values.includes(value) ? values.filter((item) => item !== value) : [...values, value]);
  const valid = step === 1 ? Boolean(arrival && departure && guests) : step === 2 ? Boolean(vehicle) : step === 3 ? Boolean(collection) : true;

  const send = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setSubmitting(true); setError(""); const form = new FormData(event.currentTarget); const fullName = String(form.get("name") || "").trim().split(/\s+/); try { const response = await fetch("/api/concierge", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ firstName: fullName[0], lastName: fullName.slice(1).join(" ") || "—", email: form.get("email"), phone: form.get("phone"), preferredContact: "Email", bestTime: "Not specified", notes: `${form.get("notes") || ""}\nAdd-ons: ${addons.map((id) => experiences.find((item) => item.id === id)?.title).join(", ") || "None"}\nVehicle: ${selectedVehicle.name}\nTravel dates: ${arrival} — ${departure}`, collection: `${selectedCollection.name} Collection`, country, guests, days: Math.max(1, Math.round((new Date(departure).getTime() - new Date(arrival).getTime()) / 86400000)), route: places.map((id) => mapPoints.find((item) => item.id === id)?.name), rate: selectedCollection.rate, website: form.get("website") }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setReference(result.reference); setDelivery(result.delivery); setStep(7); } catch (err) { setError(err instanceof Error ? err.message : "Unable to send"); } finally { setSubmitting(false); }
  };

  return <main className="planner-page">
    <header className="planner-nav"><a className="brand" href="/"><span className="brand-mark">MLT</span><span className="brand-line">Move. Live. Travel.</span></a><a href="/">×</a><div className="language-switch"><button className={locale === "en" ? "active" : ""} onClick={() => setLocale("en")}>EN</button><button className={locale === "de" ? "active" : ""} onClick={() => setLocale("de")}>DE</button></div></header>
    <section className="planner-shell">
      <aside className="planner-sidebar"><p className="section-label">MLT Journey Designer</p><h1>{t.title}</h1><p>{t.subtitle}</p><ol>{t.steps.map((label, index) => <li key={label} className={step === index + 1 ? "active" : step > index + 1 ? "done" : ""}><span>{step > index + 1 ? "✓" : String(index + 1).padStart(2, "0")}</span>{label}</li>)}</ol></aside>
      <div className="planner-content">
        {step === 1 && <div className="planner-step"><p className="step-number">01 / 06</p><h2>{t.dates}</h2><div className="planner-fields"><label>{t.country}<select value={country} onChange={(e) => setCountry(e.target.value)}><option>Italy</option><option>Austria</option><option>Germany</option></select></label><label>{t.guests}<select value={guests} onChange={(e) => setGuests(e.target.value)}><option>2 guests</option><option>3 guests</option><option>4 guests</option><option>5+ guests</option></select></label><label>{t.arrival}<input type="date" value={arrival} onChange={(e) => setArrival(e.target.value)} /></label><label>{t.departure}<input type="date" value={departure} onChange={(e) => setDeparture(e.target.value)} /></label></div></div>}
        {step === 2 && <div className="planner-step"><p className="step-number">02 / 06</p><h2>{t.chooseVehicle}</h2><div className="planner-card-grid vehicles">{fleet.map((item) => <button key={item.id} className={vehicle === item.id ? "planner-card selected" : "planner-card"} onClick={() => setVehicle(item.id)}><div className={`planner-card-image ${item.id}`}><span>{item.number}</span></div><small>{item.category}</small><strong>{item.name}</strong><p>{item.specs.join(" · ")}</p><b>{item.rate}</b></button>)}</div></div>}
        {step === 3 && <div className="planner-step"><p className="step-number">03 / 06</p><h2>{t.chooseCollection}</h2><div className="planner-card-grid collections-grid">{localizedCollections.map((item) => <button key={item.id} className={collection === item.id ? "planner-card selected" : "planner-card"} onClick={() => setCollection(item.id)}><small>{item.number} · {item.mode}</small><strong>{item.name}</strong><p>{item.eyebrow}</p><b>{item.rate}</b></button>)}</div></div>}
        {step === 4 && <div className="planner-step route-builder-step"><p className="step-number">04 / 06</p><h2>{t.chooseRoute}</h2><p className="step-hint">{t.optional}</p><div className="planner-route-builder"><div className="planner-map real-map-shell"><div className="map-country-tabs" aria-label="Filter destinations by country">{["All", "Italy", "Austria", "Germany"].map((item) => <button key={item} className={mapCountry === item ? "active" : ""} onClick={() => setMapCountry(item)}>{item === "All" && locale === "de" ? "Alle" : item}</button>)}</div><RealRouteMap selected={places} country={mapCountry} onToggle={(id) => toggle(id, places, setPlaces)} /><div className="map-legend"><span><i className="legend-selected" />{locale === "de" ? "Gewählt" : "Selected"}</span><span><i />{locale === "de" ? "Kuratierter Ort" : "Curated place"}</span><small>MLT / OpenStreetMap</small></div></div><aside className="planner-route-panel"><div className="planner-route-head"><div><small>{locale === "de" ? "Ihre Route" : "Your route"}</small><strong>{places.length} {locale === "de" ? "Stopps" : "stops"}</strong></div><button onClick={() => setPlaces([])} disabled={!places.length}>{locale === "de" ? "Löschen" : "Clear"}</button></div><div className="planner-route-list">{places.length ? places.map((id, index) => { const item = mapPoints.find((point) => point.id === id)!; return <article key={id}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{item.name}</strong><small>{item.country} · {item.type}</small></div><button onClick={() => toggle(id, places, setPlaces)} aria-label={`Remove ${item.name}`}>×</button></article>; }) : <p>{locale === "de" ? "Wählen Sie Orte auf der Karte. Ihr Concierge optimiert anschließend die schönste Fahrroute." : "Select places on the map. Your concierge will then refine the most beautiful driving route."}</p>}</div><div className="planner-route-note"><span>MLT</span><p>{locale === "de" ? "Fahrzeiten, exklusive Stellplätze und saisonale Verfügbarkeit werden persönlich geprüft." : "Drive times, exclusive stays and seasonal availability will be personally verified."}</p></div></aside></div></div>}
        {step === 5 && <div className="planner-step"><p className="step-number">05 / 06</p><h2>{t.chooseExperiences}</h2><p className="step-hint">{t.optional}</p><div className="addon-grid">{experiences.map((item) => <button key={item.id} className={addons.includes(item.id) ? "addon-option selected" : "addon-option"} onClick={() => toggle(item.id, addons, setAddons)}><span>{item.number}</span><small>{item.eyebrow}</small><strong>{item.title}</strong><b>{addons.includes(item.id) ? "✓" : "+"}</b></button>)}</div></div>}
        {step === 6 && <div className="planner-step"><p className="step-number">06 / 06</p><h2>{t.details}</h2><div className="planner-final"><div className="planner-summary"><h3>{t.summary}</h3><div><small>{t.steps[1]}</small><strong>{selectedVehicle.name}</strong></div><div><small>{t.steps[2]}</small><strong>{selectedCollection.name}</strong></div><div><small>{locale === "de" ? "Reisedauer" : "Journey length"}</small><strong>{duration} {locale === "de" ? "Tage" : "days"}</strong></div><div><small>{t.steps[3]}</small><strong>{places.length} {t.selected}</strong></div><div><small>{t.steps[4]}</small><strong>{addons.length} {t.selected}</strong></div><section className="journey-estimate"><small>{locale === "de" ? "Richtpreis" : "Indicative journey estimate"}</small><strong>{formatEuro(estimate[0], locale)} — {formatEuro(estimate[1], locale)}</strong><p>{locale === "de" ? "Exklusive Zusatzleistungen. Das finale Angebot folgt nach Verfügbarkeitsprüfung." : "Experiences quoted separately. Final proposal follows availability review."}</p></section></div><form className="planner-form" onSubmit={send}><input name="website" className="website-field" tabIndex={-1} /><label>{t.name}<input required name="name" /></label><label>{t.email}<input required type="email" name="email" /></label><label>{t.phone}<input name="phone" /></label><label>{t.notes}<textarea name="notes" rows={3} /></label><label className="consent"><input required type="checkbox" /><span>{t.consent}</span></label>{error && <p className="form-error">{error}</p>}<button className="primary-button wide" disabled={submitting}>{submitting ? t.sending : t.submit}<span>→</span></button></form></div></div>}
        {step === 7 && <div className="planner-success"><span>✓</span><p className="section-label">{delivery === "telegram" ? t.delivered : t.demo}</p><h2>{t.success}</h2><p>{t.successCopy}</p><div><small>Private request</small><strong>{reference}</strong></div><a className="primary-button" href="/">{t.return}<span>→</span></a></div>}
        {step <= 6 && <div className="planner-actions"><button onClick={() => setStep(Math.max(1, step - 1))} disabled={step === 1}>← {t.back}</button>{step > 1 && <div className="planner-live-estimate"><small>{duration} {locale === "de" ? "Tage" : "days"}</small><strong>{formatEuro(estimate[0], locale)} — {formatEuro(estimate[1], locale)}</strong></div>}<button onClick={() => setStep(Math.min(6, step + 1))} disabled={!valid}>{t.next} →</button></div>}
      </div>
    </section>
  </main>;
}
